// Tüm metinler Türkçe — eski { TR/EN } yapısı kaldırıldı.

export const translations = {
  app_title: 'Öğretmen Öğrenme Laboratuvarları',
  app_subtitle: 'MEB ÖGEDEP Dijital Ekosistem Projesi',
  tab_book: 'Randevu Al',
  tab_admin: 'Yönetim Paneli',
  tab_notifications: 'Bildirimler',
  tab_profile: 'Profilim',
  select_city: 'Bulunduğunuz İli Seçiniz',
  select_lab: 'Alan Seçiniz',
  select_date: 'Tarih Seçiniz',
  select_time_slot: 'Saat Dilimi Seçiniz',
  slots_remaining: 'Kalan Müsaitlik',
  slot_full: 'MÜSAİT DEĞİL (DOLU)',
  personal_details_header: 'Kişisel ve Rezervasyon Bilgileri',
  input_name: 'Ad',
  input_surname: 'Soyad',
  input_branch: 'Branş',
  input_work_location: 'Kurum',
  input_phone: 'Telefon',
  input_email: 'E-posta',
  input_city: 'İl',
  input_district: 'İlçe',
  input_note: 'Ek Not (İsteğe Bağlı)',
  input_password: 'Şifre',
  input_confirm_password: 'Şifre (Tekrar)',
  submit_button: 'Randevu Talebi Oluştur',
  login_title: 'Giriş Yap',
  login_subtitle: 'Öğretmen Öğrenme Laboratuvarları Rezervasyon Sistemi',
  register_title: 'Yeni Üye',
  btn_login: 'Giriş Yap',
  btn_register: 'Kayıt Ol',
  action_approve: 'Onayla',
  action_cancel: 'İptal Et',
  no_appointments: 'Henüz kayıtlı randevu yok.',
  notifications_header: 'Bildirim Geçmişi',
  notifications_empty: 'Henüz bildirim yok.',
  clear_notifications: 'Tümünü Temizle',
  err_password_mismatch: 'Şifreler uyuşmamaktadır!',
  err_user_not_found: 'Geçersiz E-posta veya Şifre!',
  err_not_approved: 'Üyeliğiniz henüz onaylanmamıştır.',
  err_email_exists: 'Bu e-posta adresi sistemde zaten kayıtlıdır.',
  err_user_not_registered: 'Bu bilgilere ait üyelik bulunamadı.',
  err_rate_limited: 'Çok fazla hatalı deneme. {secs} saniye bekleyin.',
  err_duplicate_appointment: 'Aynı stüdyo, tarih ve saat için zaten aktif bir randevunuz bulunuyor. Profilim → Randevularım sayfasından mevcut randevunuzu görüntüleyebilirsiniz.',
  err_lab_not_found: 'Seçilen alan bulunamadı. Sayfayı yenileyip tekrar deneyin.',
  err_lab_city_mismatch: 'Geçersiz randevu bilgisi. Lütfen tekrar deneyin.',
  err_slot_taken: 'Bu saat dilimi az önce başkası tarafından alındı. Başka bir saat seçin.',
  err_lab_has_appointments: 'Bu alana ait aktif randevular var. Önce randevuları iptal edin.',
  err_slot_has_appointments: 'Bu saat dilimine ait aktif randevular var. Önce randevuları iptal edin.',
  err_current_password_wrong: 'Mevcut şifreniz hatalı.',
  mark_completed: 'Tamamlandı Olarak İşaretle',
  change_password: 'Şifremi Değiştir',
  current_password: 'Mevcut Şifre',
  new_password: 'Yeni Şifre',
  password_changed: 'Şifreniz başarıyla güncellendi.',
  tab_stats: 'İstatistikler',
  stats_studio_usage: 'Alan Kullanım Sıralaması',
  stats_status_dist: 'Durum Dağılımı',
  stats_monthly: 'Aylık Trend (Son 6 Ay)',
  stats_slots: 'En Yoğun Saat Dilimleri',
  stats_no_data: 'Gösterilecek veri yok.',
  export_csv: 'CSV İndir',
  notif_target_city: 'Hedef İl (Opsiyonel)',
  notif_target_all: 'Tüm İller',
  err_kvkk_required: 'KVKK onayı zorunludur.',
  err_confirm_info_required: 'Girdiğiniz bilgilerin doğru ve eksiksiz olduğunu beyan etmeniz gerekiyor.',
  err_phone_invalid: 'Geçerli bir telefon numarası giriniz (10-11 rakam).',
  err_registration_failed: 'Kayıt sırasında bir hata oluştu.',
  err_generic: 'Bir hata oluştu.',
  err_update_failed: 'Kayıt güncellenemedi. Veritabanı izinlerini kontrol edin.',
  err_password_min_length: 'Şifre en az 8 karakter olmalıdır.',
  profile_updated: 'Profiliniz güncellendi.',
  cancellation_submitted: 'İptal talebiniz iletildi.',
  appointment_cancelled: 'Randevunuz iptal edildi.',
  appointment_success: 'Randevu talebiniz başarıyla oluşturuldu!',
  submitting: 'Gönderiliyor...',
  weekend_restriction: 'Hafta sonları randevu alınamaz. Lütfen hafta içi bir gün seçin.',
  date_restriction: 'Hafta sonları ve 60 günden ileri tarihler seçilemez.',
  province_not_found: 'İl bilgisi bulunamadı.',
  studios_not_found: 'Bu il için alan bulunamadı.',
  no_timeslots: 'Bu il için saat dilimi tanımlanmamış.',
  back_to_province: 'İl Seçimine Dön',
  back_to_studio: 'Alan Seçimine Dön',
  back_to_date: 'Tarih Seçimine Dön',
  back_to_time: 'Saat Seçimine Dön',
  province_label: 'İl',
  studio_label: 'Alan',
  date_label: 'Tarih',
  time_label: 'Saat',
  capacity_label: 'Kapasite',
  capacity_people_label: 'kişi',
  delete_lab_confirm: 'Bu alanı silmek istediğinizden emin misiniz?',
  notif_required_fields: 'Başlık ve mesaj zorunludur.',
  notif_sent: 'Bildirim gönderildi.',
  show_password: 'Şifreyi göster',
  hide_password: 'Şifreyi gizle',
  btn_yes: 'Evet',
  btn_no: 'Hayır',
  lbl_reg_date: 'Kayıt Tarihi',
  btn_nevermind: 'Vazgeç',
  processing_please_wait: 'İşleminiz gerçekleştiriliyor, lütfen bekleyiniz...',
  btn_logout: 'Çıkış',
  btn_back: 'Geri',
  toggle_dark: 'Karanlık mod',
  prev_month: 'Önceki ay',
  next_month: 'Sonraki ay',
  toggle_light: 'Aydınlık mod',
  toggle_lang: 'Dili değiştir',
  admin_type_global: 'Genel Yönetici',
  admin_type_city: 'İl Yöneticisi',
  btn_refresh: 'Yenile',
  btn_update_password: 'Şifreyi Güncelle',
  btn_save: 'Kaydet',
  btn_add: 'Ekle',
  btn_delete: 'Sil',
  select_province: 'İl Seçin',
  notif_city_only_hint: 'Yalnızca seçilen şehrin kullanıcılarına gönderilecek.',
  status_approved: 'Onaylı',
  status_pending_approval: 'Onay Bekliyor',
  filter_all_provinces: 'Tüm İller',
  filter_all_locations: 'Tüm Konumlar',
  filter_all_statuses: 'Tüm Durumlar',
  filter_clear: 'Filtreleri Temizle',
  filter_date: 'Tarih:',
  filter_date_from: 'Başlangıç tarihi',
  filter_date_to: 'Bitiş tarihi',
  clear: 'Temizle',
  tab_appointments_label: 'Randevular',
  tab_studios_label: 'Alanlar',
  tab_slots_label: 'Saat Dilimleri',
  tab_approvals_label: 'Üye Onayları',
  tab_send_notif: 'Bildirim Gönder',
  stat_total: 'Toplam',
  stat_pending_status: 'Bekleyen Randevu',
  stat_approved_status: 'Onaylandı',
  stat_cancelled_status: 'İptal',
  search_placeholder: 'Ad, e-posta, alan ara...',
  search_user_placeholder: 'İsim veya e-posta ile ara...',
  records_count: 'kayıt',
  shown: 'gösteriliyor',
  show_more: 'Daha Fazla Göster',
  remaining: 'kaldı',
  lbl_studio: 'Alan',
  lbl_province: 'İl',
  lbl_date: 'Tarih',
  lbl_time: 'Saat',
  lbl_branch: 'Branş',
  lbl_institution: 'Kurum',
  lbl_note: 'Not',
  lbl_status: 'Durum',
  lbl_created: 'Oluşturma',
  lbl_action: 'İşlem',
  audit_detail_city_notifs: 'Şehir: {city}',
  audit_detail_all_notifs: 'Tüm bildirimler silindi',
  audit_detail_force_deleted: '{name} (zorla silindi)',
  lbl_details: 'Detay',
  lbl_actor: 'Yetkili',
  lbl_size_small: 'Küçük',
  lbl_size_medium: 'Orta',
  lbl_size_large: 'Büyük',
  lbl_size_xlarge: 'Çok Büyük',
  lbl_size_normal: 'Normal',
  lbl_font_serif: 'Serif (klasik)',
  lbl_font_sans: 'Sans (modern)',
  lbl_align_center: 'Ortalı',
  lbl_align_left: 'Sola Hizalı',
  slot_mgmt_title: 'Saat Dilimi Yönetimi',
  slot_add_new: 'Yeni Saat Dilimi Ekle',
  slot_none: 'Henüz saat dilimi eklenmemiş.',
  slot_placeholder: 'Örn: 09:00 - 10:00',
  slot_required_fields: 'Lütfen tüm alanları doldurun.',
  studio_add: '+ Alan Ekle',
  studio_new: 'Yeni Alan',
  studio_edit: 'Alanı Düzenle',
  studio_city_required: 'İl ve alan adı zorunludur.',
  studio_name_required: 'Alan adı zorunludur.',
  pending_users_title: 'Onay Bekleyenler',
  approved_users_title: 'Onaylı Üyeler',
  no_pending_users: 'Onay bekleyen kullanıcı yok.',
  no_approved_users: 'Onaylı üye yok.',
  notif_new: 'Yeni Bildirim Gönder',
  notif_lbl_type: 'Tür',
  notif_lbl_title: 'Başlık',
  notif_lbl_message: 'Mesaj',
  notif_type_system: 'Sistem',
  notif_type_reminder: 'Hatırlatma',
  notif_type_alert: 'Uyarı',
  notif_send_btn: 'Bildirimi Gönder',
  notif_title_placeholder: 'Bildirim başlığı...',
  notif_msg_placeholder: 'Bildirim mesajı...',
  notif_send_email_label: 'Ayrıca e-posta olarak da gönder',
  notif_email_recipients_count: '{n} kullanıcıya ulaşacak',
  notif_email_no_recipients: 'Bu hedef kitle için onaylı kullanıcı yok.',
  notif_email_result: 'Bildirim oluşturuldu — {sent} e-posta gönderildi, {failed} başarısız.',
  notif_email_sending: 'E-postalar gönderiliyor...',
  audit_fetch_more_from_server: 'Sunucudan daha eski kayıtları yükle',
  restore_notifications: 'Geri Al',
  updating: 'Güncelleniyor...',
  restore_notifications_hint: '{n} gizlenmiş bildirim',
  err_phone_format: 'Geçerli bir Türk telefon numarası giriniz (05XXXXXXXXX).',
  confirm_approve_appt: 'Bu randevuyu onaylamak istediğinizden emin misiniz?',
  confirm_cancel_appt: 'Bu randevuyu iptal etmek istediğinizden emin misiniz?',
  confirm_complete_appt: 'Bu randevuyu tamamlandı olarak işaretlemek istediğinizden emin misiniz?',
  confirm_approve_user: 'Bu üyeyi onaylamak istediğinizden emin misiniz?',
  confirm_revoke_user: 'Bu üyeyi sistemden silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
  tab_workshops: 'Atölyeler',
  workshop_add: 'Atölye Ekle',
  workshop_new: 'Yeni Atölye',
  workshop_name_label: 'Atölye Adı',
  workshop_date_label: 'Tarih',
  workshop_time_label: 'Saat',
  workshop_capacity_label: 'Kapasite',
  workshop_location_label: 'Konum',
  workshop_desc_label: 'Açıklama',
  workshop_delete_confirm: 'Bu atölyeyi silmek istediğinizden emin misiniz?',
  workshop_added: 'Atölye eklendi.',
  workshop_name_required: 'Atölye adı zorunludur.',
  no_workshops: 'Henüz atölye eklenmemiş.',
  lbl_capacity_slot: 'Kapasite (slot başına)',
  lbl_branches: 'Branşlar',
  lbl_branches_placeholder: 'Örn: Fen, Matematik',
  province_label_req: 'İl',
  studio_name_label_req: 'Alan Adı',
  lbl_description: 'Açıklama',
  lbl_location: 'Konum',
  lbl_district: 'İlçe',
  btn_edit: 'Düzenle',
  btn_retry: 'Yeniden Dene',
  lbl_membership_status: 'Üyelik Durumu',
  btn_approve_member: 'Üyeliği Onayla',
  btn_revoke_member: 'Üyeliği İptal Et',
  btn_reject_member: 'Reddet & Sil',
  placeholder_email: 'E-posta adresiniz',
  placeholder_password: 'Şifreniz',
  placeholder_registered_email: 'Kayıtlı e-posta adresiniz',
  notif_appt_approved: 'Randevunuz Onaylandı',
  notif_appt_cancelled: 'Randevunuz İptal Edildi',
  loading_signin: 'Giriş yapılıyor...',
  loading_registering: 'Kaydediliyor...',
  loading_looking_up: 'Sorgulanıyor...',
  loading_saving: 'Kaydediliyor...',
  upcoming_appointments: 'Yaklaşan Randevularım',
  no_upcoming_appointments: 'Yaklaşan randevu yok.',
  past_appointments: 'Geçmiş Randevular',
  kvkk_title: 'KVKK Aydınlatma Metni',
  kvkk_consent_suffix: '\'ni okudum ve kabul ediyorum. *',
  kvkk_agree_btn: 'Okudum, Onaylıyorum',
  btn_close: 'Kapat',
  btn_ok: 'Tamam',
  reg_success_title: 'Başvurunuz Alındı',
  reg_success_msg: 'Üyelik talebiniz alınmıştır. Bilgileriniz kontrol edildikten sonra üyeliğiniz onaylanacaktır.',
  cancel_modal_title: 'İptal Talebi',
  cancel_modal_subtitle: 'İptal sebebinizi belirtin (isteğe bağlı).',
  cancel_reason_placeholder: 'İptal sebebinizi yazın...',
  btn_submit: 'Gönder',
  lbl_cancel_reason: 'İptal notu',
  btn_request_cancellation: 'İptal Talebi Gönder',
  data_load_failed: 'Veriler yüklenemedi.',
  realtime_error: 'Gerçek zamanlı bağlantı kurulamadı. Veriler otomatik güncellenmeyebilir.',
  clear_notifications_confirm: 'Tüm bildirimler kalıcı olarak silinecek. Emin misiniz?',
  menu_open: 'Menüyü aç',
  menu_close: 'Menüyü kapat',
  pw_requirement_hint: '(Şifreniz en az 8 karakter, büyük/küçük harf, rakam ve özel karakter içermelidir. Örnek: !, @, #, $, %)',
  pw_req_length: 'En az 8 karakter',
  pw_req_upper: 'Büyük harf (A-Z)',
  pw_req_lower: 'Küçük harf (a-z)',
  pw_req_number: 'Rakam (0-9)',
  pw_req_special: 'Özel karakter (!, @, #, $, %)',
  err_password_weak: 'Şifreniz en az 8 karakter, büyük/küçük harf, rakam ve özel karakter içermelidir.',
  btn_reset_password: 'Şifre Sıfırla',
  reset_pw_title: 'Şifre Sıfırla',
  reset_pw_success: 'Şifre başarıyla sıfırlandı.',
  tab_admins: 'Yöneticiler',
  tab_audit: 'Denetim',
  admin_add: '+ Yönetici Ekle',
  admin_new: 'Yeni Yönetici',
  admin_delete_confirm: 'Bu yöneticiyi silmek istediğinizden emin misiniz?',
  admin_added: 'Yönetici eklendi.',
  admin_search_placeholder: 'İsim veya e-posta ara...',
  lbl_role: 'Rol',
  lbl_phone: 'Telefon',
  err_admin_required_fields: 'İsim, e-posta ve şifre zorunludur.',
  err_city_required: 'İl yöneticisi için il seçimi zorunludur.',
  no_admins: 'Yönetici bulunamadı.',
  approve_cancellation: 'İptali Onayla',
  deny_cancellation: 'Talebi Reddet',
  confirm_approve_cancellation: 'Kullanıcının iptal talebini onaylayıp randevuyu iptal etmek istediğinizden emin misiniz?',
  confirm_deny_cancellation: 'İptal talebini reddetmek istediğinizden emin misiniz? Randevu "Onaylı" durumuna döner.',
  action_success_approved: 'Randevu onaylandı.',
  action_success_cancelled: 'Randevu iptal edildi.',
  action_success_completed: 'Randevu tamamlandı olarak işaretlendi.',
  action_success_cancellation_approved: 'İptal talebi onaylandı.',
  action_success_cancellation_denied: 'İptal talebi reddedildi.',
  session_timeout_title: 'Oturum Zaman Aşımı',
  session_timeout_msg: 'Uzun süre işlem yapmadınız. {t} saniye sonra otomatik çıkış yapılacak.',
  session_continue: 'Devam Et',
  notif_search_placeholder: 'Bildirim ara...',
  audit_search_placeholder: 'Kişi, e-posta veya detay ara...',
  lbl_cancellation_reason: 'İptal Sebebi',
  bulk_approve: 'Seçilenleri Onayla',
  bulk_cancel: 'Seçilenleri İptal Et',
  bulk_selected: '{n} seçili',
  bulk_deselect: 'Seçimi Kaldır',
  bulk_select_all: 'Tümünü seç',
  bulk_select_one: 'Seç:',
  view_calendar: 'Takvim',
  view_list: 'Liste',
  workshop_register: 'Kayıt Ol',
  workshop_unregister: 'Kaydı İptal Et',
  workshop_registered_badge: 'Kayıtlısınız',
  workshop_full: 'Kontenjan Dolu',
  workshop_register_success: 'Atölye kaydınız oluşturuldu.',
  workshop_unregister_success: 'Atölye kaydınız iptal edildi.',
  workshop_registrants_title: 'Kayıtlılar',
  workshop_no_registrants: 'Henüz kayıtlı yok.',
  err_workshop_full: 'Atölye kapasitesi dolu.',
  err_already_registered: 'Bu atölye için zaten kayıtlısınız.',
  city_change_note: 'Şehir değişikliği aktif randevularınızı etkilemez.',
  tab_messages: 'Mesajlar',
  msg_to_city_admin: 'İl Yöneticisi',
  msg_to_global_admin: 'Genel Yönetici',
  msg_no_conversations: 'Henüz mesaj yok.',
  msg_no_messages: 'Mesaj gönder.',
  msg_placeholder: 'Mesajınızı yazın...',
  msg_send: 'Gönder',
  msg_from_user: 'Kullanıcıdan',
  msg_conversations_title: 'Konuşmalar',
  msg_all_cities: 'Tüm İller',
  msg_user_to_city: 'Kullanıcı → İl',
  msg_city_to_global: 'İl → Genel',
  msg_user_to_global: 'Kullanıcı → Genel',
  msg_unread_badge: 'okunmamış',
  msg_new_message_notif: 'Yeni mesajınız var.',
  tab_closed_days: 'Kapalı Günler',
  closed_day_add: 'Kapalı Gün Ekle',
  closed_day_reason: 'Sebep (opsiyonel)',
  closed_day_added: 'Kapalı gün eklendi.',
  closed_day_deleted: 'Kapalı gün silindi.',
  no_closed_days: 'Kapalı gün yok.',
  err_date_closed: 'Bu tarih kapalı olarak işaretlenmiş.',
  err_date_holiday: 'Bu tarih resmi tatildir.',
  err_sunday: 'Pazar günleri randevu alınamaz.',
  lbl_holiday: 'Resmi Tatil',
  today_bookings_badge: 'bugün aktif',
  tab_email: 'E-posta Gönder',
  email_subject: 'Konu',
  email_subject_ph: 'E-posta konusu...',
  email_body: 'İçerik',
  email_body_ph: 'E-posta içeriği...',
  email_recipients_users: 'Kullanıcılar',
  email_recipients_admins: 'Yöneticiler',
  email_send_users: 'Kullanıcılara Gönder',
  email_send_admins: 'Yöneticilere Gönder',
  email_select_all: 'Tümünü Seç',
  email_deselect_all: 'Seçimi Kaldır',
  email_search_ph: 'İsim veya e-posta ara...',
  email_no_match: 'Eşleşen kayıt yok.',
  email_sending: 'Gönderiliyor...',
  email_sent_ok: '{n} alıcıya başarıyla gönderildi.',
  email_sent_partial: '{sent}/{total} alıcıya gönderildi ({failed} başarısız).',
  email_err_no_recipients: 'Lütfen en az bir alıcı seçin.',
  email_err_subject: 'Konu ve içerik zorunludur.',
  email_err_send: 'Gönderme başarısız oldu.',
  email_selected_n: '{n} seçili',
  waitlist_added: 'Bekleme listesine eklendiniz. Yer açıldığında bildirim alacaksınız.',
  waitlist_removed: 'Bekleme listesinden çıkarıldınız.',
  waitlist_join: 'Bekleme Listesine Ekle',
  waitlist_on_list: '✓ Bekleme Listesinde',
  admin_cannot_delete_self: 'Kendi hesabınızı silemezsiniz.',
  admin_self_indicator: '(siz)',
  admin_edit_title: 'Yönetici Düzenle',
  admin_edit_role_warning: '⚠️ Rol değişiyor: {from} → {to}. Kaydet\'e basarak onaylıyorsunuz.',
  workshop_edit_title: 'Atölyeyi Düzenle',
  workshop_attendance_attended: 'Katıldı',
  workshop_attendance_not_yet: 'Katılmadı',
  workshop_remove_reg: 'Kaydı Sil',
  slot_invalid_format: 'Geçersiz format. Örn: 09:00 - 17:00',
  slot_start_before_end: 'Başlangıç saati bitiş saatinden önce olmalıdır.',
  slot_already_exists: 'Bu saat dilimi zaten mevcut.',
  notif_history_title: 'Bildirim Geçmişi',
  notif_history_empty: 'Bildirim bulunamadı.',
  appt_edit_datetime: 'Tarih / Saat Değiştir',
  appt_edit_current: 'mevcut',
  err_add_user_required_fields: 'Ad, soyad, e-posta, şifre ve il zorunludur.',
  user_added: 'Üye eklendi.',
  csv_import: 'CSV İçe Aktar',
  btn_add_member: 'Üye Ekle',
  csv_import_result: '{ok} eklendi, {fail} başarısız',
  csv_errors_more: '... ve {n} daha',
  csv_import_pw_hint: 'Her kullanıcıya benzersiz geçici şifre atanır. Kullanıcılar ilk girişte şifre değiştirmek zorunda kalacak.',
  csv_err_missing_field: 'Satır {n}: eksik alan',
  csv_err_invalid_email: 'Satır {n}: geçersiz e-posta ({email})',
  csv_err_city_not_found: 'Satır {n}: il bulunamadı ({city})',
  csv_err_row_generic: 'Satır {n} ({email}): {error}',
  csv_err_read_file: 'Dosya okunamadı.',
  csv_err_already_exists: 'Satır {n} ({email}): bu e-posta zaten kayıtlı',
  user_new: 'Yeni Üye',
  lbl_password_required: 'Şifre *',
  lbl_confirm_password_required: 'Şifre Tekrar *',
  add_user_pw_hint: 'Kullanıcı ilk girişte bu şifreyi değiştirmek zorunda kalacak.',
  copy_pw_modal_title: 'Geçici Şifre',
  copy_pw_modal_desc: 'Bu geçici şifreyi güvenli bir şekilde kullanıcıyla paylaşın. Pencere kapatıldıktan sonra tekrar görüntülenemez.',
  copy_pw_btn_copy: 'Kopyala',
  copy_pw_btn_copied: 'Kopyalandı!',
  copy_pw_done_btn: 'Tamam, Kaydettim',
  email_p_credentials_shared: 'Giriş bilgileriniz yöneticiniz tarafından güvenli bir şekilde iletilecektir.',
  select_all: 'Tümünü Seç',
  approve_selected_n: 'Seçilenleri Onayla ({n})',
  err_bulk_approve_failed: '{n} üye onaylanamadı.',
  confirm_bulk_approve: '{n} üyeyi onaylamak istediğinizden emin misiniz?',
  active_appts_will_cancel: 'aktif randevu iptal edilecek',
  loading: 'Yükleniyor...',
  btn_update: 'Güncelle',
  btn_continue: 'Devam Et',
  btn_remove: 'Çıkar',
  btn_yes_remove: 'Evet, Çıkar',
  btn_sign_out: 'Çıkış Yap',
  btn_choose_file: 'Dosya Seç',
  photo_hint: 'Fotoğraf: JPEG, PNG, WebP veya GIF · Maks. 1 MB',
  photo_hint_extended: 'Fotoğraf: JPEG, PNG, WebP, GIF · Maks. 1 MB',
  avatar_upload_hint: 'JPEG, PNG, WebP veya GIF · Maks. 1 MB',
  alt_profile_photo: 'profil fotoğrafı',
  lbl_full_name: 'Ad Soyad',
  err_invalid_email: 'Geçerli bir e-posta adresi girin.',
  err_phone_format: 'Geçerli bir telefon numarası girin. Örnek: 05XX XXX XX XX',
  tab_certificate: 'Sertifika',
  location_placeholder: 'Konum (isteğe bağlı), örn: Gölbaşı BİLSEM',
  appt_rescheduled: 'Randevu yeniden zamanlandı.',
  pending_cancellation_title: 'Bekleyen İptal Talepleriniz',
  waiting_admin_review: 'Yönetici onayı bekleniyor.',
  no_appts_on_date: 'Bu tarihte randevu yok.',
  appts_cancelled_n: 'İptal Edilmiş ({n})',
  waitlist_title_n: 'Bekleme Listesi ({n})',
  my_workshop_regs_n: 'Atölye Kayıtlarım ({n})',
  workshop_date_tbd: 'Tarih belirlenmedi',
  my_certificates_n: 'Sertifikalarım ({n})',
  reschedule_title: 'Yeniden Zamanla',
  reschedule_step1: '1. Yeni Tarih Seçin',
  reschedule_step2: '2. Saat Seçin',
  slot_free_count: 'boş',
  city_change_title: 'Şehir Değişikliği',
  city_change_warning: 'Aktif randevularınız var. Şehri değiştirirseniz mevcut randevularınız etkilenmez ancak yeni şehirde oluşturmanız gerekebilir. Devam etmek istiyor musunuz?',
  waitlist_remove_title: 'Bekleme Listesinden Çıkar',
  waitlist_remove_confirm: 'Bu bekleme listesi kaydını silmek istediğinizden emin misiniz?',
  force_pw_title: 'Şifrenizi Değiştirin',
  force_pw_subtitle: 'Yöneticiniz şifrenizi sıfırladı. Devam edebilmek için yeni bir şifre belirlemeniz gerekiyor.',
  lbl_temp_password: 'Geçici Şifre (Admin Tarafından Verilen)',
  notif_filter_all_types: 'Tüm Türler',
  notif_type_appointment: 'Randevu',
  clear_notif_city_confirm: 'Yalnızca "{city}" iline ait bildirimler kalıcı olarak silinecek. Emin misiniz?',
  view_certificate: 'Sertifikamı Görüntüle',
  awaiting_attendance: 'Yönetici katılımınızı onayladığında sertifikanız burada görünecek.',
  upcoming_workshops: 'Yaklaşan Atölyeler',
  past_workshops: 'Geçmiş Atölyeler',
  err_conv_start: 'Konuşma başlatılamadı. Lütfen tekrar deneyin.',
  err_msgs_load: 'Mesajlar yüklenemedi. Lütfen tekrar deneyin.',
  err_msg_send: 'Mesaj gönderilemedi.',
  slot_time_required: 'Saat dilimi gereklidir.',
  slot_no_slots_yet: 'Henüz saat dilimi eklenmedi.',
  closed_day_already_exists: 'Bu tarih zaten kapalı olarak işaretlenmiş.',
  closed_days_auto_note: 'Pazar günleri ve resmi tatiller otomatik olarak kapalıdır. Aşağıdan ek kapalı günler ekleyebilirsiniz.',
  lbl_date_required: 'Tarih *',
  closed_day_reason_ph: 'Tatil, bakım...',
  all_provinces_global: 'Tüm İller (global)',
  err_logo_too_large: 'Logo dosyası 2 MB\'dan büyük olamaz.',
  cert_default_title: 'KATILIM SERTİFİKASI',
  cert_default_body: '{{tarih}} tarihinde {{konum}} adresinde gerçekleştirilen "{{atolye}}" atölyesine katıldığınız için bu belgeyi almaya hak kazandınız.',
  err_cert_required: 'Başlık, kurum ve metin zorunludur.',
  cert_template_saved: 'Şablon kaydedildi.',
  cert_email_confirm: '"{workshop}" atölyesindeki {count} katılımcıya sertifika e-postası gönderilecek. Onaylıyor musunuz?',
  cert_template_title: 'Sertifika Şablonu',
  cert_show_form: 'Formu Göster',
  cert_preview: 'Önizleme',
  cert_vars_hint: 'Değişkenler: {{katilimci}} · katılımcı adı, {{atolye}} · atölye adı, {{tarih}} · tarih, {{konum}} · yer',
  lbl_logo_optional: 'Logo (isteğe bağlı)',
  url_placeholder: 'https://...',
  logo_upload_hint: 'Maks. 2 MB · URL veya dosya yükle',
  alt_cert_logo: 'Sertifika logosu',
  lbl_logo_size: 'Logo Boyutu',
  lbl_institution_name: 'Kurum Adı',
  placeholder_multiline: 'Alt satır için Enter kullanın',
  lbl_cert_title: 'Sertifika Başlığı',
  lbl_title_size: 'Başlık Punto',
  lbl_cert_body: 'Sertifika Metni',
  lbl_body_size: 'Metin Punto',
  lbl_alignment: 'Hizalama',
  lbl_name_font: 'İsim Fontu',
  lbl_signatory_name: 'İmzalayan Adı',
  lbl_signatory_title: 'Unvan',
  lbl_footer_optional: 'Alt Metin (isteğe bağlı)',
  btn_save_template: 'Şablonu Kaydet',
  cert_email_section: 'Sertifika E-postası Gönder',
  cert_email_desc: 'Seçili atölyeye katılmış (attended) kullanıcılara sertifika hazır bildirimi gönderir.',
  select_workshop: 'Atölye Seçin',
  cert_attendee_count: 'Katılımcı: {n} kişi',
  cert_emails_sent: '{sent}/{total} e-posta gönderildi',
  btn_print_pdf: 'Yazdır / PDF',
  show_less: 'Daha az',
  show_all_n: 'Tümünü gör ({n})',
  stats_top_users: 'En Çok Randevu Alan Kullanıcılar',
  stat_upcoming: 'Yaklaşan',
  stat_past: 'Geçmiş',
  stat_no_date: 'Tarifsiz',
  workshop_updated: 'Atölye güncellendi.',
  workshop_delete_suffix: 'kayıtlı katılımcı silinecek',
  err_time_range_invalid: 'Saat formatı geçersiz veya bitiş saati başlangıçtan önce. Örnek: 09:00 - 17:00',
  err_capacity_min: 'Kapasite en az 1 olmalıdır.',
  err_capacity_min_n: 'Kapasite en az {n} olmalıdır ({n} kayıtlı katılımcı var).',
  lbl_general: 'Genel',
  lbl_audit_log: 'Denetim Kaydı',
  err_load_audit: 'Denetim kayıtları yüklenemedi. Sayfayı yenileyin.',
  filter_all_actions: 'Tüm İşlemler',
  lbl_date_colon: 'Tarih:',
  btn_clear: 'Temizle',
  no_records_found: 'Kayıt bulunamadı.',
  record_added: 'Kayıt eklendi.',
  record_updated: 'Kayıt güncellendi.',
  btn_fix_data: 'Veriyi Düzenle',
  migration_confirm: 'Veri göçü geri alınamaz. Devam etmek istiyor musunuz?',
  migration_completed_errors: 'Göç tamamlandı ancak {n} kayıtta hata oluştu.',
  lbl_edit_role_province: 'Rol / İl Düzenle',
  btn_change_datetime: 'Tarih/Saat Değiştir',
  confirm_appointment_title: 'Randevuyu Onayla',
  btn_confirm: 'Onayla',
  btn_go_back: 'Geri Dön',
  cert_greeting: 'Sayın',
  notif_unread_count: '{n} okunmamış bildirim',
  err_file_too_large: 'Dosya 1 MB\'dan büyük olamaz.',
  err_file_type: 'Yalnızca JPEG, PNG, WebP veya GIF yükleyebilirsiniz.',
  err_slot_full: 'Bu slot dolu.',
  err_already_on_waitlist: 'Zaten bekleme listelesindesiniz.',
  notif_reminder_title: 'Yaklaşan Randevu Hatırlatması',
  notif_new_member_title: 'Yeni Üye Başvurusu',
  notif_appt_approved_title: 'Randevu Onaylandı',
  notif_appt_cancelled_title: 'Randevu İptal Edildi',
  notif_cancel_requested_title: 'Randevu İptal Talebi',
  notif_cancellation_denied_title: 'İptal Talebi Reddedildi',
  notif_membership_approved_title: 'Üyelik Onaylandı',
  notif_admin_added_title: 'Yeni Yönetici Eklendi',
  notif_admin_pw_reset_title: 'Yönetici Şifresi Sıfırlandı',
  notif_appt_rescheduled_title: 'Randevu Yeniden Planlandı',
  notif_waitlist_available_title: 'Bekleme Listesi: Slot Açıldı',
  notif_reminder_msg: '{lab} - {date} {slot} tarihli randevunuz yaklaşıyor.',
  notif_new_member_msg: '{name} ({email}) kayıt talebinde bulundu.',
  notif_appt_approved_msg: '{teacher} adlı öğretmenin {lab} için {date} tarihli randevusu onaylandı.',
  notif_appt_cancelled_admin_msg: '{teacher} adlı öğretmenin {lab} için {date} tarihli randevusu iptal edildi.',
  notif_appt_cancelled_user_msg: '{teacher} adlı öğretmen, {lab} için {date} tarihli bekleyen randevusunu iptal etti.',
  notif_cancel_requested_msg: '{teacher} adlı öğretmen, {lab} için {date} tarihli randevusunu iptal talep etti.',
  notif_cancellation_denied_msg: '{teacher} adlı öğretmenin {lab} için {date} tarihli iptal talebi reddedildi.',
  notif_membership_approved_msg: '{name} adlı öğretmenin üyeliği onaylandı.',
  notif_admin_added_msg: '{name} ({email}) yönetici olarak eklendi.',
  notif_admin_pw_reset_msg: '{name} ({email}) adlı yöneticinin şifresi genel yönetici tarafından sıfırlandı.',
  notif_waitlist_available_msg: '{lab} - {date} {slot} için bir yer açıldı. Lütfen randevu alın.',
  notif_revoke_user_title: '[{city}] Üyelik İptal Edildi',
  notif_revoke_user_msg: '{teacher} adlı öğretmenin üyeliği iptal edildi.',
  email_subj_account_created: 'Hesabınız Oluşturuldu – MEB ÖGEDEP',
  email_subj_password_updated: 'Şifreniz Güncellendi – MEB ÖGEDEP',
  email_subj_membership_approved: 'Üyeliğiniz Onaylandı – MEB ÖGEDEP',
  email_subj_appt_approved: 'Randevunuz Onaylandı – {lab}',
  email_subj_appt_cancelled: 'Randevunuz İptal Edildi – {lab}',
  email_subj_cancellation_denied: 'İptal Talebiniz Reddedildi – MEB ÖGEDEP',
  email_subj_workshop_confirmed: 'Atölye Kaydınız Oluşturuldu – {name}',
  email_subj_workshop_cancelled: 'Atölye Kaydınız İptal Edildi – {name}',
  email_subj_admin_created: 'Yönetici Hesabınız Oluşturuldu – MEB ÖGEDEP',
  email_subj_temp_password: 'Geçici Şifreniz – MEB ÖGEDEP',
  email_subj_cert_ready: 'Sertifikanız Hazır – {workshop}',
  email_dear: 'Sayın',
  email_footer_auto: 'Bu e-posta otomatik olarak gönderilmiştir. Lütfen yanıtlamayınız.',
  email_link_go_to_system: 'Sisteme Giriş Yap',
  email_lbl_password: 'Şifre',
  email_p_dear_participant: 'Sayın katılımcı,',
  email_p_cert_ready: '<strong>{workshop}</strong> atölyesine katılımınız tamamlanmış olup sertifikanız hazırdır.',
  email_p_cert_download: 'Sertifikanızı indirmek için sisteme giriş yapın ve profilinizi ziyaret edin.',
  email_p_login_credentials: 'Giriş bilgileriniz:',
  email_p_must_change_pw: 'Sisteme giriş yaptığınızda yeni bir şifre belirlemeniz istenecektir.',
  email_p_account_created: 'MEB ÖGEDEP sistemine yönetici tarafından hesabınız oluşturulmuştur.',
  email_p_membership_approved: 'MEB ÖGEDEP Öğretmen Öğrenme Laboratuvarları sistemine üyeliğiniz onaylanmıştır.',
  email_p_membership_can_book: 'Artık sisteme giriş yaparak randevu alabilir ve atölye programlarına kayıt olabilirsiniz.',
  email_p_appt_approved: '{lab} için randevunuz onaylanmıştır.',
  email_p_appt_date: 'Tarih:',
  email_p_appt_time: 'Saat:',
  email_p_appt_location: 'Konum:',
  email_p_appt_cancelled: '{lab} için {date} tarihli randevunuz yönetici tarafından iptal edilmiştir.',
  email_p_appt_cancelled_nodate: '{lab} için randevunuz yönetici tarafından iptal edilmiştir.',
  email_p_book_new_appt: 'Yeni randevu almak için sistemi ziyaret edebilirsiniz.',
  email_p_cancellation_denied: '{lab} için {date} tarihli randevunuza ait iptal talebiniz reddedilmiştir.',
  email_p_cancellation_denied_nd: '{lab} için randevunuza ait iptal talebiniz reddedilmiştir.',
  email_p_appt_still_approved: 'Randevunuz Onaylı statüsünde devam etmektedir.',
  email_p_workshop_confirmed: '"{workshop}" atölyesine kaydınız başarıyla oluşturulmuştur.',
  email_p_workshop_visit: 'Atölye programı hakkında daha fazla bilgi için sistemi ziyaret edebilirsiniz.',
  email_p_workshop_cancelled: '"{workshop}" atölyesine ait kaydınız iptal edilmiştir.',
  email_p_workshop_other: 'Başka bir atölye programına kayıt olmak için sistemi ziyaret edebilirsiniz.',
  email_p_admin_created: 'MEB ÖGEDEP sistemine {role} olarak hesabınız oluşturulmuştur.',
  email_role_global: 'Genel Yönetici',
  email_role_city: 'İl Yöneticisi',
  email_p_pw_reset_user: 'Yönetici tarafından şifreniz sıfırlanmıştır. Yeni geçici şifreniz aşağıda yer almaktadır:',
  email_p_pw_reset_admin: 'Genel yönetici tarafından hesabınızın şifresi sıfırlanmıştır. Yeni şifreniz:',
  email_p_pw_reset_request: 'Şifre sıfırlama talebiniz alınmıştır. Geçici şifreniz:',
  email_p_pw_reset_prompt: 'Sisteme giriş yaptığınızda yeni bir şifre belirlemeniz istenecektir.',
  forgot_pw_admin_help: 'Şifrenizi unuttuysanız sistem yöneticinizle iletişime geçin.',
  sample_name: 'Ahmet Yılmaz',
  sample_workshop: 'Örnek Atölye Adı',
  sample_date: '1 Haziran 2025',
  sample_location: 'İstanbul',
}

export const STATUS_COLORS = {
  "PENDING": "bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-300",
  "APPROVED": "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300",
  "CANCELLED": "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300",
  "CANCELLATION_REQUESTED": "bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
  "COMPLETED": "bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300"
}

export const STATUS_LABELS = {
  PENDING: 'Beklemede',
  APPROVED: 'Onaylandı',
  CANCELLED: 'İptal Edildi',
  CANCELLATION_REQUESTED: 'İptal Talebi',
  COMPLETED: 'Tamamlandı',
}

// `lang` parametresi geriye dönük uyum için kabul edilir; göz ardı edilir.
export function t(key, _lang) {
  return translations[key] ?? key
}

export function getLocale(_language) { return 'tr-TR' }

// YYYY-MM-DD → DD.MM.YYYY
export function formatDate(dateStr) {
  if (!dateStr) return ''
  const parts = String(dateStr).split('-')
  if (parts.length !== 3) return dateStr
  return `${parts[2]}.${parts[1]}.${parts[0]}`
}

// epoch ms → DD.MM.YYYY HH:MM
export function formatTimestamp(ts) {
  if (!ts) return ''
  try {
    const d = new Date(Number(ts))
    const day = String(d.getDate()).padStart(2, '0')
    const month = String(d.getMonth() + 1).padStart(2, '0')
    const year = d.getFullYear()
    const hours = String(d.getHours()).padStart(2, '0')
    const mins = String(d.getMinutes()).padStart(2, '0')
    return `${day}.${month}.${year} ${hours}:${mins}`
  } catch {
    return ts
  }
}
