export const translations = {
  app_title: { TR: 'Öğretmen Öğrenme Laboratuvarları', EN: 'Teacher Learning Labs' },
  app_subtitle: { TR: 'MEB ÖGEDEP Dijital Ekosistem Projesi', EN: 'MEB ÖGEDEP Digital Ecosystem Project' },
  tab_book: { TR: 'Randevu Al', EN: 'Book Slot' },
  tab_admin: { TR: 'Yönetim Paneli', EN: 'Admin Panel' },
  tab_notifications: { TR: 'Bildirimler', EN: 'Notifications' },
  tab_profile: { TR: 'Profilim', EN: 'My Profile' },
  select_city: { TR: 'Bulunduğunuz İli Seçiniz', EN: 'Select Your Current City' },
  select_lab: { TR: 'Alan Seçiniz', EN: 'Select Area' },
  select_date: { TR: 'Tarih Seçiniz', EN: 'Select Date' },
  select_time_slot: { TR: 'Saat Dilimi Seçiniz', EN: 'Select Time Slot' },
  slots_remaining: { TR: 'Kalan Müsaitlik', EN: 'Remaining Slots' },
  slot_full: { TR: 'MÜSAİT DEĞİL (DOLU)', EN: 'NOT AVAILABLE (FULL)' },
  personal_details_header: { TR: 'Kişisel ve Rezervasyon Bilgileri', EN: 'Personal & Reservation Information' },
  input_name: { TR: 'Ad', EN: 'First Name' },
  input_surname: { TR: 'Soyad', EN: 'Last Name' },
  input_branch: { TR: 'Branş', EN: 'Branch' },
  input_work_location: { TR: 'Kurum', EN: 'Institution' },
  input_phone: { TR: 'Telefon', EN: 'Phone' },
  input_email: { TR: 'E-posta', EN: 'Email' },
  input_city: { TR: 'İl', EN: 'City' },
  input_district: { TR: 'İlçe', EN: 'District' },
  input_note: { TR: 'Ek Not (İsteğe Bağlı)', EN: 'Extra Note (Optional)' },
  input_password: { TR: 'Şifre', EN: 'Password' },
  input_confirm_password: { TR: 'Şifre (Tekrar)', EN: 'Confirm Password' },
  submit_button: { TR: 'Randevu Talebi Oluştur', EN: 'Create Reservation Request' },
  login_title: { TR: 'Giriş Yap', EN: 'Sign In' },
  login_subtitle: { TR: 'Öğretmen Öğrenme Laboratuvarları Rezervasyon Sistemi', EN: 'Teacher Learning Labs Reservation System' },
  register_title: { TR: 'Yeni Üye', EN: 'Create Account' },
  btn_login: { TR: 'Giriş Yap', EN: 'Sign In' },
  btn_register: { TR: 'Kayıt Ol', EN: 'Create Account' },
  action_approve: { TR: 'Onayla', EN: 'Approve' },
  action_cancel: { TR: 'İptal Et', EN: 'Cancel' },
  no_appointments: { TR: 'Henüz kayıtlı randevu yok.', EN: 'No appointments found.' },
  notifications_header: { TR: 'Bildirim Geçmişi', EN: 'Notification History' },
  notifications_empty: { TR: 'Henüz bildirim yok.', EN: 'No notifications yet.' },
  clear_notifications: { TR: 'Tümünü Temizle', EN: 'Clear All' },
  err_password_mismatch: { TR: 'Şifreler uyuşmamaktadır!', EN: 'Passwords do not match!' },
  err_user_not_found: { TR: 'Geçersiz E-posta veya Şifre!', EN: 'Invalid Email or Password!' },
  err_not_approved: { TR: 'Üyeliğiniz henüz onaylanmamıştır.', EN: 'Your membership has not been approved yet.' },
  err_email_exists: { TR: 'Bu e-posta adresi sistemde zaten kayıtlıdır.', EN: 'This email address is already registered in the system.' },
  err_user_not_registered: { TR: 'Bu bilgilere ait üyelik bulunamadı.', EN: 'No membership found with this information.' },
  err_rate_limited: { TR: 'Çok fazla hatalı deneme. {secs} saniye bekleyin.', EN: 'Too many failed attempts. Wait {secs} seconds.' },
  err_duplicate_appointment: { TR: 'Bu stüdyo, tarih ve saat için zaten aktif bir randevunuz var.', EN: 'You already have an active appointment for this studio, date and time slot.' },
  err_lab_not_found: { TR: 'Seçilen alan bulunamadı. Sayfayı yenileyip tekrar deneyin.', EN: 'Selected lab not found. Please refresh and try again.' },
  err_lab_city_mismatch: { TR: 'Geçersiz randevu bilgisi. Lütfen tekrar deneyin.', EN: 'Invalid appointment data. Please try again.' },
  err_slot_taken: { TR: 'Bu saat dilimi az önce başkası tarafından alındı. Başka bir saat seçin.', EN: 'This time slot was just taken by someone else. Please choose a different time.' },
  err_lab_has_appointments: { TR: 'Bu alana ait aktif randevular var. Önce randevuları iptal edin.', EN: 'This area has active appointments. Cancel them first.' },
  err_slot_has_appointments: { TR: 'Bu saat dilimine ait aktif randevular var. Önce randevuları iptal edin.', EN: 'This time slot has active appointments. Cancel them first.' },
  err_current_password_wrong: { TR: 'Mevcut şifreniz hatalı.', EN: 'Current password is incorrect.' },
  mark_completed: { TR: 'Tamamlandı Olarak İşaretle', EN: 'Mark as Completed' },
  change_password: { TR: 'Şifremi Değiştir', EN: 'Change Password' },
  current_password: { TR: 'Mevcut Şifre', EN: 'Current Password' },
  new_password: { TR: 'Yeni Şifre', EN: 'New Password' },
  password_changed: { TR: 'Şifreniz başarıyla güncellendi.', EN: 'Your password has been updated successfully.' },
  tab_stats: { TR: 'İstatistikler', EN: 'Statistics' },
  stats_studio_usage: { TR: 'Alan Kullanım Sıralaması', EN: 'Area Usage Ranking' },
  stats_status_dist: { TR: 'Durum Dağılımı', EN: 'Status Distribution' },
  stats_monthly: { TR: 'Aylık Trend (Son 6 Ay)', EN: 'Monthly Trend (Last 6 Months)' },
  stats_slots: { TR: 'En Yoğun Saat Dilimleri', EN: 'Busiest Time Slots' },
  stats_no_data: { TR: 'Gösterilecek veri yok.', EN: 'No data to display.' },
  export_csv: { TR: 'CSV İndir', EN: 'Download CSV' },
  notif_target_city: { TR: 'Hedef İl (Opsiyonel)', EN: 'Target Province (Optional)' },
  notif_target_all: { TR: 'Tüm İller', EN: 'All Provinces' },
  forgot_password: { TR: 'Şifremi Unuttum', EN: 'Forgot Password' },
  forgot_subtitle: { TR: 'Sisteme kayıtlı e-posta adresinizi girin.', EN: 'Enter your registered email address.' },
  forgot_verify_btn: { TR: 'Sorgula', EN: 'Look Up' },
  forgot_new_password_subtitle: { TR: 'Yeni şifrenizi belirleyin.', EN: 'Set your new password.' },
  forgot_save_btn: { TR: 'Şifreyi Kaydet', EN: 'Save Password' },
  forgot_success: { TR: 'Şifreniz başarıyla güncellendi. Giriş yapabilirsiniz.', EN: 'Your password has been updated. You can now sign in.' },
  back_to_login: { TR: 'Giriş Sayfasına Dön', EN: 'Back to Sign In' },
  err_kvkk_required: { TR: 'KVKK onayı zorunludur.', EN: 'KVKK consent is required.' },
  err_phone_invalid: { TR: 'Geçerli bir telefon numarası giriniz (10-11 rakam).', EN: 'Please enter a valid phone number (10-11 digits).' },
  err_registration_failed: { TR: 'Kayıt sırasında bir hata oluştu.', EN: 'An error occurred during registration.' },
  err_generic: { TR: 'Bir hata oluştu.', EN: 'An error occurred.' },
  err_update_failed: { TR: 'Kayıt güncellenemedi. Veritabanı izinlerini kontrol edin.', EN: 'Record could not be updated. Check database permissions.' },
  err_password_min_length: { TR: 'Şifre en az 8 karakter olmalıdır.', EN: 'Password must be at least 8 characters.' },
  profile_updated: { TR: 'Profiliniz güncellendi.', EN: 'Profile updated successfully.' },
  cancellation_submitted: { TR: 'İptal talebiniz iletildi.', EN: 'Your cancellation request has been submitted.' },
  appointment_cancelled: { TR: 'Randevunuz iptal edildi.', EN: 'Appointment cancelled.' },
  appointment_success: { TR: 'Randevu talebiniz başarıyla oluşturuldu!', EN: 'Your reservation request was created successfully!' },
  submitting: { TR: 'Gönderiliyor...', EN: 'Submitting...' },
  weekend_restriction: { TR: 'Hafta sonları randevu alınamaz. Lütfen hafta içi bir gün seçin.', EN: 'Appointments cannot be made on weekends. Please select a weekday.' },
  date_restriction: { TR: 'Hafta sonları ve 60 günden ileri tarihler seçilemez.', EN: 'Weekends and dates beyond 60 days are not available.' },
  province_not_found: { TR: 'İl bilgisi bulunamadı.', EN: 'No province information found.' },
  studios_not_found: { TR: 'Bu il için alan bulunamadı.', EN: 'No areas found for this province.' },
  no_timeslots: { TR: 'Bu il için saat dilimi tanımlanmamış.', EN: 'No time slots defined for this province.' },
  back_to_province: { TR: 'İl Seçimine Dön', EN: 'Back to Province Selection' },
  back_to_studio: { TR: 'Alan Seçimine Dön', EN: 'Back to Area Selection' },
  back_to_date: { TR: 'Tarih Seçimine Dön', EN: 'Back to Date Selection' },
  back_to_time: { TR: 'Saat Seçimine Dön', EN: 'Back to Time Selection' },
  province_label: { TR: 'İl', EN: 'Province' },
  studio_label: { TR: 'Alan', EN: 'Area' },
  date_label: { TR: 'Tarih', EN: 'Date' },
  time_label: { TR: 'Saat', EN: 'Time' },
  capacity_label: { TR: 'Kapasite', EN: 'Capacity' },
  capacity_people_label: { TR: 'kişi', EN: 'people' },
  delete_lab_confirm: { TR: 'Bu alanı silmek istediğinizden emin misiniz?', EN: 'Are you sure you want to delete this area?' },
  notif_required_fields: { TR: 'Başlık ve mesaj zorunludur.', EN: 'Title and message are required.' },
  notif_sent: { TR: 'Bildirim gönderildi.', EN: 'Notification sent.' },
  btn_yes: { TR: 'Evet', EN: 'Yes' },
  btn_nevermind: { TR: 'Vazgeç', EN: 'Cancel' },
  processing_please_wait: { TR: 'İşleminiz gerçekleştiriliyor, lütfen bekleyiniz...', EN: 'Processing, please wait...' },
  btn_logout: { TR: 'Çıkış', EN: 'Logout' },
  btn_back: { TR: 'Geri', EN: 'Back' },
  toggle_dark: { TR: 'Karanlık mod', EN: 'Dark mode' },
  toggle_lang: { TR: 'Dili değiştir', EN: 'Switch language' },
  admin_type_global: { TR: 'Genel Yönetici', EN: 'Global Admin' },
  admin_type_city: { TR: 'İl Yöneticisi', EN: 'Province Admin' },
  btn_refresh: { TR: 'Yenile', EN: 'Refresh' },
  btn_update_password: { TR: 'Şifreyi Güncelle', EN: 'Update Password' },
  btn_save: { TR: 'Kaydet', EN: 'Save' },
  btn_add: { TR: 'Ekle', EN: 'Add' },
  btn_delete: { TR: 'Sil', EN: 'Delete' },
  select_province: { TR: 'İl Seçin', EN: 'Select Province' },
  notif_city_only_hint: { TR: 'Yalnızca seçilen şehrin kullanıcılarına gönderilecek.', EN: 'Will be sent only to users in the selected city.' },
  status_approved: { TR: 'Onaylı', EN: 'Approved' },
  status_pending_approval: { TR: 'Onay Bekliyor', EN: 'Pending Approval' },
  filter_all_provinces: { TR: 'Tüm İller', EN: 'All Provinces' },
  filter_all_locations: { TR: 'Tüm Konumlar', EN: 'All Locations' },
  filter_all_statuses: { TR: 'Tüm Durumlar', EN: 'All Statuses' },
  filter_clear: { TR: 'Filtreleri Temizle', EN: 'Clear Filters' },
  filter_date: { TR: 'Tarih:', EN: 'Date:' },
  clear: { TR: 'Temizle', EN: 'Clear' },
  tab_appointments_label: { TR: 'Randevular', EN: 'Appointments' },
  tab_studios_label: { TR: 'Alanlar', EN: 'Areas' },
  tab_slots_label: { TR: 'Saat Dilimleri', EN: 'Time Slots' },
  tab_approvals_label: { TR: 'Üye Onayları', EN: 'User Approvals' },
  tab_send_notif: { TR: 'Bildirim Gönder', EN: 'Send Notification' },
  stat_total: { TR: 'Toplam', EN: 'Total' },
  stat_pending_status: { TR: 'Bekleyen Randevu', EN: 'Pending Appts' },
  stat_approved_status: { TR: 'Onaylandı', EN: 'Approved' },
  stat_cancelled_status: { TR: 'İptal', EN: 'Cancelled' },
  search_placeholder: { TR: 'Ad, e-posta, alan ara...', EN: 'Search name, email, area...' },
  search_user_placeholder: { TR: 'İsim veya e-posta ile ara...', EN: 'Search by name or email...' },
  records_count: { TR: 'kayıt', EN: 'records' },
  shown: { TR: 'gösteriliyor', EN: 'shown' },
  show_more: { TR: 'Daha Fazla Göster', EN: 'Show More' },
  remaining: { TR: 'kaldı', EN: 'remaining' },
  lbl_studio: { TR: 'Alan', EN: 'Area' },
  lbl_province: { TR: 'İl', EN: 'Province' },
  lbl_date: { TR: 'Tarih', EN: 'Date' },
  lbl_time: { TR: 'Saat', EN: 'Time' },
  lbl_branch: { TR: 'Branş', EN: 'Branch' },
  lbl_institution: { TR: 'Kurum', EN: 'Institution' },
  lbl_note: { TR: 'Not', EN: 'Note' },
  slot_mgmt_title: { TR: 'Saat Dilimi Yönetimi', EN: 'Time Slot Management' },
  slot_add_new: { TR: 'Yeni Saat Dilimi Ekle', EN: 'Add New Time Slot' },
  slot_none: { TR: 'Henüz saat dilimi eklenmemiş.', EN: 'No time slots added yet.' },
  slot_placeholder: { TR: 'Örn: 09:00 - 10:00', EN: 'E.g.: 09:00 - 10:00' },
  slot_required_fields: { TR: 'Lütfen tüm alanları doldurun.', EN: 'Please fill all fields.' },
  studio_add: { TR: '+ Alan Ekle', EN: '+ Add Area' },
  studio_new: { TR: 'Yeni Alan', EN: 'New Area' },
  studio_edit: { TR: 'Alanı Düzenle', EN: 'Edit Area' },
  studio_city_required: { TR: 'İl ve alan adı zorunludur.', EN: 'Province and area name are required.' },
  studio_name_required: { TR: 'Alan adı zorunludur.', EN: 'Area name is required.' },
  pending_users_title: { TR: 'Onay Bekleyenler', EN: 'Pending Approval' },
  approved_users_title: { TR: 'Onaylı Üyeler', EN: 'Approved Members' },
  no_pending_users: { TR: 'Onay bekleyen kullanıcı yok.', EN: 'No users pending approval.' },
  no_approved_users: { TR: 'Onaylı üye yok.', EN: 'No approved members.' },
  notif_new: { TR: 'Yeni Bildirim Gönder', EN: 'Send New Notification' },
  notif_lbl_type: { TR: 'Tür', EN: 'Type' },
  notif_lbl_title: { TR: 'Başlık', EN: 'Title' },
  notif_lbl_message: { TR: 'Mesaj', EN: 'Message' },
  notif_type_system: { TR: 'Sistem', EN: 'System' },
  notif_type_reminder: { TR: 'Hatırlatma', EN: 'Reminder' },
  notif_type_alert: { TR: 'Uyarı', EN: 'Alert' },
  notif_send_btn: { TR: 'Bildirimi Gönder', EN: 'Send Notification' },
  notif_title_placeholder: { TR: 'Bildirim başlığı...', EN: 'Notification title...' },
  notif_msg_placeholder: { TR: 'Bildirim mesajı...', EN: 'Notification message...' },
  confirm_approve_appt: { TR: 'Bu randevuyu onaylamak istediğinizden emin misiniz?', EN: 'Are you sure you want to approve this appointment?' },
  confirm_cancel_appt: { TR: 'Bu randevuyu iptal etmek istediğinizden emin misiniz?', EN: 'Are you sure you want to cancel this appointment?' },
  confirm_complete_appt: { TR: 'Bu randevuyu tamamlandı olarak işaretlemek istediğinizden emin misiniz?', EN: 'Mark this appointment as completed?' },
  confirm_approve_user: { TR: 'Bu üyeyi onaylamak istediğinizden emin misiniz?', EN: 'Are you sure you want to approve this member?' },
  confirm_revoke_user: { TR: 'Bu üyeyi sistemden silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.', EN: 'Are you sure you want to delete this member? This cannot be undone.' },
  tab_workshops: { TR: 'Atölyeler', EN: 'Workshops' },
  workshop_add: { TR: 'Atölye Ekle', EN: 'Add Workshop' },
  workshop_new: { TR: 'Yeni Atölye', EN: 'New Workshop' },
  workshop_name_label: { TR: 'Atölye Adı', EN: 'Workshop Name' },
  workshop_date_label: { TR: 'Tarih', EN: 'Date' },
  workshop_time_label: { TR: 'Saat', EN: 'Time' },
  workshop_capacity_label: { TR: 'Kapasite', EN: 'Capacity' },
  workshop_location_label: { TR: 'Konum', EN: 'Location' },
  workshop_desc_label: { TR: 'Açıklama', EN: 'Description' },
  workshop_delete_confirm: { TR: 'Bu atölyeyi silmek istediğinizden emin misiniz?', EN: 'Are you sure you want to delete this workshop?' },
  workshop_added: { TR: 'Atölye eklendi.', EN: 'Workshop added.' },
  workshop_name_required: { TR: 'Atölye adı zorunludur.', EN: 'Workshop name is required.' },
  no_workshops: { TR: 'Henüz atölye eklenmemiş.', EN: 'No workshops added yet.' },
  lbl_capacity_slot: { TR: 'Kapasite (slot başına)', EN: 'Capacity (per slot)' },
  lbl_branches: { TR: 'Branşlar', EN: 'Branches' },
  lbl_branches_placeholder: { TR: 'Örn: Fen, Matematik', EN: 'E.g.: Science, Math' },
  province_label_req: { TR: 'İl', EN: 'Province' },
  studio_name_label_req: { TR: 'Alan Adı', EN: 'Area Name' },
  lbl_description: { TR: 'Açıklama', EN: 'Description' },
  lbl_location: { TR: 'Konum', EN: 'Location' },
  lbl_district: { TR: 'İlçe', EN: 'District' },
  btn_edit: { TR: 'Düzenle', EN: 'Edit' },
  btn_retry: { TR: 'Yeniden Dene', EN: 'Retry' },
  lbl_membership_status: { TR: 'Üyelik Durumu', EN: 'Membership Status' },
  btn_approve_member: { TR: 'Üyeliği Onayla', EN: 'Approve Membership' },
  btn_revoke_member: { TR: 'Üyeliği İptal Et', EN: 'Revoke Membership' },
  btn_reject_member: { TR: 'Reddet & Sil', EN: 'Reject & Delete' },
  placeholder_email: { TR: 'E-posta adresiniz', EN: 'Your email address' },
  placeholder_password: { TR: 'Şifreniz', EN: 'Your password' },
  placeholder_registered_email: { TR: 'Kayıtlı e-posta adresiniz', EN: 'Your registered email' },
  notif_appt_approved: { TR: 'Randevunuz Onaylandı', EN: 'Appointment Approved' },
  notif_appt_cancelled: { TR: 'Randevunuz İptal Edildi', EN: 'Appointment Cancelled' },
  loading_signin: { TR: 'Giriş yapılıyor...', EN: 'Signing in...' },
  loading_registering: { TR: 'Kaydediliyor...', EN: 'Registering...' },
  loading_looking_up: { TR: 'Sorgulanıyor...', EN: 'Looking up...' },
  loading_saving: { TR: 'Kaydediliyor...', EN: 'Saving...' },
  upcoming_appointments: { TR: 'Yaklaşan Randevularım', EN: 'Upcoming Appointments' },
  no_upcoming_appointments: { TR: 'Yaklaşan randevu yok.', EN: 'No upcoming appointments.' },
  past_appointments: { TR: 'Geçmiş Randevular', EN: 'Past Appointments' },
  kvkk_title: { TR: 'KVKK Aydınlatma Metni', EN: 'KVKK Information Text' },
  kvkk_consent_suffix: { TR: "'ni okudum ve kabul ediyorum. *", EN: ' — I have read and agree. *' },
  kvkk_agree_btn: { TR: 'Okudum, Onaylıyorum', EN: 'I Read and Agree' },
  btn_close: { TR: 'Kapat', EN: 'Close' },
  btn_ok: { TR: 'Tamam', EN: 'OK' },
  reg_success_title: { TR: 'Başvurunuz Alındı', EN: 'Application Received' },
  reg_success_msg: { TR: 'Üyelik talebiniz alınmıştır. Bilgileriniz kontrol edildikten sonra üyeliğiniz onaylanacaktır.', EN: 'Your membership request has been received. Your membership will be approved after your information is verified.' },
  cancel_modal_title: { TR: 'İptal Talebi', EN: 'Cancellation Request' },
  cancel_modal_subtitle: { TR: 'İptal sebebinizi belirtin (isteğe bağlı).', EN: 'State your cancellation reason (optional).' },
  cancel_reason_placeholder: { TR: 'İptal sebebinizi yazın...', EN: 'Write your reason...' },
  btn_submit: { TR: 'Gönder', EN: 'Submit' },
  lbl_cancel_reason: { TR: 'İptal notu', EN: 'Cancel reason' },
  btn_request_cancellation: { TR: 'İptal Talebi Gönder', EN: 'Request Cancellation' },
  data_load_failed: { TR: 'Veriler yüklenemedi.', EN: 'Failed to load data.' },
  clear_notifications_confirm: { TR: 'Tüm bildirimler kalıcı olarak silinecek. Emin misiniz?', EN: 'All notifications will be permanently deleted. Are you sure?' },
  menu_open: { TR: 'Menüyü aç', EN: 'Open menu' },
  menu_close: { TR: 'Menüyü kapat', EN: 'Close menu' },
  pw_requirement_hint: { TR: '(Şifreniz en az 8 karakter, büyük/küçük harf, rakam ve özel karakter içermelidir. Örnek: !, @, #, $, %)', EN: '(Password must be at least 8 characters and include uppercase, lowercase, a number and a special character. E.g.: !, @, #, $, %)' },
  pw_req_length: { TR: 'En az 8 karakter', EN: 'At least 8 characters' },
  pw_req_upper: { TR: 'Büyük harf (A-Z)', EN: 'Uppercase letter (A-Z)' },
  pw_req_lower: { TR: 'Küçük harf (a-z)', EN: 'Lowercase letter (a-z)' },
  pw_req_number: { TR: 'Rakam (0-9)', EN: 'Number (0-9)' },
  pw_req_special: { TR: 'Özel karakter (!, @, #, $, %)', EN: 'Special character (!, @, #, $, %)' },
  err_password_weak: { TR: 'Şifreniz en az 8 karakter, büyük/küçük harf, rakam ve özel karakter içermelidir.', EN: 'Password must contain at least 8 characters, uppercase/lowercase letters, a number and a special character.' },
  btn_reset_password: { TR: 'Şifre Sıfırla', EN: 'Reset Password' },
  reset_pw_title: { TR: 'Şifre Sıfırla', EN: 'Reset Password' },
  reset_pw_success: { TR: 'Şifre başarıyla sıfırlandı.', EN: 'Password reset successfully.' },
  tab_admins: { TR: 'Yöneticiler', EN: 'Admins' },
  tab_audit: { TR: 'Denetim', EN: 'Audit' },
  admin_add: { TR: '+ Yönetici Ekle', EN: '+ Add Admin' },
  admin_new: { TR: 'Yeni Yönetici', EN: 'New Admin' },
  admin_delete_confirm: { TR: 'Bu yöneticiyi silmek istediğinizden emin misiniz?', EN: 'Are you sure you want to delete this admin?' },
  admin_added: { TR: 'Yönetici eklendi.', EN: 'Admin added.' },
  admin_search_placeholder: { TR: 'İsim veya e-posta ara...', EN: 'Search by name or email...' },
  lbl_role: { TR: 'Rol', EN: 'Role' },
  lbl_phone: { TR: 'Telefon', EN: 'Phone' },
  err_admin_required_fields: { TR: 'İsim, e-posta ve şifre zorunludur.', EN: 'Name, email and password are required.' },
  err_city_required: { TR: 'İl yöneticisi için il seçimi zorunludur.', EN: 'Province selection is required for province admin.' },
  no_admins: { TR: 'Yönetici bulunamadı.', EN: 'No admins found.' },
  approve_cancellation: { TR: 'İptali Onayla', EN: 'Approve Cancellation' },
  deny_cancellation: { TR: 'Talebi Reddet', EN: 'Deny Request' },
  confirm_approve_cancellation: { TR: 'Kullanıcının iptal talebini onaylayıp randevuyu iptal etmek istediğinizden emin misiniz?', EN: 'Approve the cancellation request and cancel the appointment?' },
  confirm_deny_cancellation: { TR: 'İptal talebini reddetmek istediğinizden emin misiniz? Randevu "Onaylı" durumuna döner.', EN: 'Deny this cancellation request? The appointment will return to Approved.' },
  action_success_approved: { TR: 'Randevu onaylandı.', EN: 'Appointment approved.' },
  action_success_cancelled: { TR: 'Randevu iptal edildi.', EN: 'Appointment cancelled.' },
  action_success_completed: { TR: 'Randevu tamamlandı olarak işaretlendi.', EN: 'Appointment marked as completed.' },
  action_success_cancellation_approved: { TR: 'İptal talebi onaylandı.', EN: 'Cancellation approved.' },
  action_success_cancellation_denied: { TR: 'İptal talebi reddedildi.', EN: 'Cancellation denied.' },
  // Session timeout
  session_timeout_title: { TR: 'Oturum Zaman Aşımı', EN: 'Session Timeout' },
  session_timeout_msg: { TR: 'Uzun süre işlem yapmadınız. {t} saniye sonra otomatik çıkış yapılacak.', EN: 'You have been inactive. Auto-logout in {t} seconds.' },
  session_continue: { TR: 'Devam Et', EN: 'Stay Logged In' },
  // Notification search
  notif_search_placeholder: { TR: 'Bildirim ara...', EN: 'Search notifications...' },
  // Audit search
  audit_search_placeholder: { TR: 'Kişi, e-posta veya detay ara...', EN: 'Search by person, email or detail...' },
  // Cancellation reason label (admin view)
  lbl_cancellation_reason: { TR: 'İptal Sebebi', EN: 'Cancellation Reason' },
  // Bulk operations
  bulk_approve: { TR: 'Seçilenleri Onayla', EN: 'Approve Selected' },
  bulk_cancel: { TR: 'Seçilenleri İptal Et', EN: 'Cancel Selected' },
  bulk_selected: { TR: '{n} seçili', EN: '{n} selected' },
  bulk_deselect: { TR: 'Seçimi Kaldır', EN: 'Deselect All' },
  // Calendar view
  view_calendar: { TR: 'Takvim', EN: 'Calendar' },
  view_list: { TR: 'Liste', EN: 'List' },
  // Workshop registration
  workshop_register: { TR: 'Kayıt Ol', EN: 'Register' },
  workshop_unregister: { TR: 'Kaydı İptal Et', EN: 'Unregister' },
  workshop_registered_badge: { TR: 'Kayıtlısınız', EN: 'Registered' },
  workshop_full: { TR: 'Kontenjan Dolu', EN: 'Workshop Full' },
  workshop_register_success: { TR: 'Atölye kaydınız oluşturuldu.', EN: 'Workshop registration successful.' },
  workshop_unregister_success: { TR: 'Atölye kaydınız iptal edildi.', EN: 'Workshop registration cancelled.' },
  workshop_registrants_title: { TR: 'Kayıtlılar', EN: 'Registrants' },
  workshop_no_registrants: { TR: 'Henüz kayıtlı yok.', EN: 'No registrants yet.' },
  err_workshop_full: { TR: 'Atölye kapasitesi dolu.', EN: 'Workshop is at full capacity.' },
  err_already_registered: { TR: 'Bu atölye için zaten kayıtlısınız.', EN: 'You are already registered for this workshop.' },
  // City change in profile
  city_change_note: { TR: 'Şehir değişikliği aktif randevularınızı etkilemez.', EN: 'City change does not affect existing appointments.' },
  // Messaging
  tab_messages:           { TR: 'Mesajlar',                    EN: 'Messages' },
  msg_to_city_admin:      { TR: 'İl Yöneticisi',              EN: 'City Admin' },
  msg_to_global_admin:    { TR: 'Genel Yönetici',             EN: 'Global Admin' },
  msg_no_conversations:   { TR: 'Henüz mesaj yok.',           EN: 'No messages yet.' },
  msg_no_messages:        { TR: 'Mesaj gönder.',              EN: 'Send a message.' },
  msg_placeholder:        { TR: 'Mesajınızı yazın...',        EN: 'Type your message...' },
  msg_send:               { TR: 'Gönder',                     EN: 'Send' },
  msg_from_user:          { TR: 'Kullanıcıdan',               EN: 'From user' },
  msg_conversations_title: { TR: 'Konuşmalar',               EN: 'Conversations' },
  msg_all_cities:         { TR: 'Tüm İller',                  EN: 'All Provinces' },
  msg_user_to_city:       { TR: 'Kullanıcı → İl',            EN: 'User → City' },
  msg_city_to_global:     { TR: 'İl → Genel',                EN: 'City → Global' },
  msg_user_to_global:     { TR: 'Kullanıcı → Genel',         EN: 'User → Global' },
  msg_unread_badge:       { TR: 'okunmamış',                  EN: 'unread' },
  msg_new_message_notif:  { TR: 'Yeni mesajınız var.',        EN: 'You have a new message.' },
  // Closed days
  tab_closed_days:      { TR: 'Kapalı Günler',              EN: 'Closed Days' },
  closed_day_add:       { TR: 'Kapalı Gün Ekle',            EN: 'Add Closed Day' },
  closed_day_reason:    { TR: 'Sebep (opsiyonel)',           EN: 'Reason (optional)' },
  closed_day_added:     { TR: 'Kapalı gün eklendi.',         EN: 'Closed day added.' },
  closed_day_deleted:   { TR: 'Kapalı gün silindi.',         EN: 'Closed day removed.' },
  no_closed_days:       { TR: 'Kapalı gün yok.',             EN: 'No closed days.' },
  err_date_closed:      { TR: 'Bu tarih kapalı olarak işaretlenmiş.', EN: 'This date is closed.' },
  err_date_holiday:     { TR: 'Bu tarih resmi tatildir.',    EN: 'This is a public holiday.' },
  err_sunday:           { TR: 'Pazar günleri randevu alınamaz.', EN: 'Appointments cannot be made on Sundays.' },
  lbl_holiday:          { TR: 'Resmi Tatil',                 EN: 'Public Holiday' },
  today_bookings_badge: { TR: 'bugün aktif',                 EN: 'active today' },
}

export const STATUS_COLORS = {
  PENDING: 'bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-300',
  APPROVED: 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300',
  CANCELLED: 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300',
  CANCELLATION_REQUESTED: 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300',
  COMPLETED: 'bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300',
}

export const STATUS_LABELS = {
  PENDING: { TR: 'Beklemede', EN: 'Pending' },
  APPROVED: { TR: 'Onaylandı', EN: 'Approved' },
  CANCELLED: { TR: 'İptal Edildi', EN: 'Cancelled' },
  CANCELLATION_REQUESTED: { TR: 'İptal Talebi', EN: 'Cancel Requested' },
  COMPLETED: { TR: 'Tamamlandı', EN: 'Completed' },
}

export function t(key, lang = 'TR') {
  const entry = translations[key]
  if (!entry) return key
  return entry[lang] || entry['TR'] || key
}

// Convert YYYY-MM-DD → DD.MM.YYYY
export function formatDate(dateStr) {
  if (!dateStr) return ''
  const parts = String(dateStr).split('-')
  if (parts.length !== 3) return dateStr
  return `${parts[2]}.${parts[1]}.${parts[0]}`
}

// Format epoch ms timestamp → DD.MM.YYYY HH:MM
export function formatTimestamp(ts) {
  if (!ts) return ''
  try {
    const d = new Date(Number(ts))
    const day = String(d.getDate()).padStart(2, '0')
    const month = String(d.getMonth() + 1).padStart(2, '0')
    const year = d.getFullYear()
    const hours = String(d.getHours()).padStart(2, '0')
    const mins = String(d.getMinutes()).padStart(2, '0')
    return `${day}.${month}.${year} ${hours}:${mins}`
  } catch {
    return ts
  }
}


