export const translations = {
  app_title: { TR: 'Öğretmen Öğrenme Laboratuvarları', EN: 'Teacher Learning Labs' },
  app_subtitle: { TR: 'MEB ÖGEDEP Dijital Ekosistem Projesi', EN: 'MEB ÖGEDEP Digital Ecosystem Project' },
  tab_book: { TR: 'Randevu Al', EN: 'Book Slot' },
  tab_admin: { TR: 'Yönetim Paneli', EN: 'Admin Panel' },
  tab_notifications: { TR: 'Bildirimler', EN: 'Notifications' },
  tab_profile: { TR: 'Profilim', EN: 'My Profile' },
  select_city: { TR: 'Bulunduğunuz İli Seçiniz', EN: 'Select Your Current City' },
  select_lab: { TR: 'Alan Seçiniz', EN: 'Select Area' },
  select_date: { TR: 'Tarih Seçiniz', EN: 'Select Date' },
  select_time_slot: { TR: 'Saat Dilimi Seçiniz', EN: 'Select Time Slot' },
  slots_remaining: { TR: 'Kalan Müsaitlik', EN: 'Remaining Slots' },
  slot_full: { TR: 'MÜSAİT DEĞİL (DOLU)', EN: 'NOT AVAILABLE (FULL)' },
  personal_details_header: { TR: 'Kişisel ve Rezervasyon Bilgileri', EN: 'Personal & Reservation Information' },
  input_name: { TR: 'Ad', EN: 'First Name' },
  input_surname: { TR: 'Soyad', EN: 'Last Name' },
  input_branch: { TR: 'Branş', EN: 'Branch' },
  input_work_location: { TR: 'Kurum', EN: 'Institution' },
  input_phone: { TR: 'Telefon', EN: 'Phone' },
  input_email: { TR: 'E-posta', EN: 'Email' },
  input_city: { TR: 'İl', EN: 'City' },
  input_district: { TR: 'İlçe', EN: 'District' },
  input_note: { TR: 'Ek Not (İsteğe Bağlı)', EN: 'Extra Note (Optional)' },
  input_password: { TR: 'Şifre', EN: 'Password' },
  input_confirm_password: { TR: 'Şifre (Tekrar)', EN: 'Confirm Password' },
  submit_button: { TR: 'Randevu Talebi Oluştur', EN: 'Create Reservation Request' },
  login_title: { TR: 'Giriş Yap', EN: 'Sign In' },
  login_subtitle: { TR: 'Öğretmen Öğrenme Laboratuvarları Rezervasyon Sistemi', EN: 'Teacher Learning Labs Reservation System' },
  register_title: { TR: 'Yeni Üye', EN: 'Create Account' },
  btn_login: { TR: 'Giriş Yap', EN: 'Sign In' },
  btn_register: { TR: 'Kayıt Ol', EN: 'Create Account' },
  action_approve: { TR: 'Onayla', EN: 'Approve' },
  action_cancel: { TR: 'İptal Et', EN: 'Cancel' },
  no_appointments: { TR: 'Henüz kayıtlı randevu yok.', EN: 'No appointments found.' },
  notifications_header: { TR: 'Bildirim Geçmişi', EN: 'Notification History' },
  notifications_empty: { TR: 'Henüz bildirim yok.', EN: 'No notifications yet.' },
  clear_notifications: { TR: 'Tümünü Temizle', EN: 'Clear All' },
  err_password_mismatch: { TR: 'Şifreler uyuşmamaktadır!', EN: 'Passwords do not match!' },
  err_user_not_found: { TR: 'Geçersiz E-posta veya Şifre!', EN: 'Invalid Email or Password!' },
  err_not_approved: { TR: 'Üyeliğiniz henüz onaylanmamıştır.', EN: 'Your membership has not been approved yet.' },
  err_email_exists: { TR: 'Bu e-posta adresi sistemde zaten kayıtlıdır.', EN: 'This email address is already registered in the system.' },
  err_user_not_registered: { TR: 'Bu bilgilere ait üyelik bulunamadı.', EN: 'No membership found with this information.' },
  err_rate_limited: { TR: 'Çok fazla hatalı deneme. {secs} saniye bekleyin.', EN: 'Too many failed attempts. Wait {secs} seconds.' },
  err_duplicate_appointment: { TR: 'Bu stüdyo, tarih ve saat için zaten aktif bir randevunuz var.', EN: 'You already have an active appointment for this studio, date and time slot.' },
  err_lab_not_found: { TR: 'Seçilen alan bulunamadı. Sayfayı yenileyip tekrar deneyin.', EN: 'Selected lab not found. Please refresh and try again.' },
  err_lab_city_mismatch: { TR: 'Geçersiz randevu bilgisi. Lütfen tekrar deneyin.', EN: 'Invalid appointment data. Please try again.' },
  err_slot_taken: { TR: 'Bu saat dilimi az önce başkası tarafından alındı. Başka bir saat seçin.', EN: 'This time slot was just taken by someone else. Please choose a different time.' },
  err_lab_has_appointments: { TR: 'Bu alana ait aktif randevular var. Önce randevuları iptal edin.', EN: 'This area has active appointments. Cancel them first.' },
  err_slot_has_appointments: { TR: 'Bu saat dilimine ait aktif randevular var. Önce randevuları iptal edin.', EN: 'This time slot has active appointments. Cancel them first.' },
  err_current_password_wrong: { TR: 'Mevcut şifreniz hatalı.', EN: 'Current password is incorrect.' },
  mark_completed: { TR: 'Tamamlandı Olarak İşaretle', EN: 'Mark as Completed' },
  change_password: { TR: 'Şifremi Değiştir', EN: 'Change Password' },
  current_password: { TR: 'Mevcut Şifre', EN: 'Current Password' },
  new_password: { TR: 'Yeni Şifre', EN: 'New Password' },
  password_changed: { TR: 'Şifreniz başarıyla güncellendi.', EN: 'Your password has been updated successfully.' },
  tab_stats: { TR: 'İstatistikler', EN: 'Statistics' },
  stats_studio_usage: { TR: 'Alan Kullanım Sıralaması', EN: 'Area Usage Ranking' },
  stats_status_dist: { TR: 'Durum Dağılımı', EN: 'Status Distribution' },
  stats_monthly: { TR: 'Aylık Trend (Son 6 Ay)', EN: 'Monthly Trend (Last 6 Months)' },
  stats_slots: { TR: 'En Yoğun Saat Dilimleri', EN: 'Busiest Time Slots' },
  stats_no_data: { TR: 'Gösterilecek veri yok.', EN: 'No data to display.' },
  export_csv: { TR: 'CSV İndir', EN: 'Download CSV' },
  notif_target_city: { TR: 'Hedef İl (Opsiyonel)', EN: 'Target Province (Optional)' },
  notif_target_all: { TR: 'Tüm İller', EN: 'All Provinces' },
  err_kvkk_required: { TR: 'KVKK onayı zorunludur.', EN: 'KVKK consent is required.' },
  err_phone_invalid: { TR: 'Geçerli bir telefon numarası giriniz (10-11 rakam).', EN: 'Please enter a valid phone number (10-11 digits).' },
  err_registration_failed: { TR: 'Kayıt sırasında bir hata oluştu.', EN: 'An error occurred during registration.' },
  err_generic: { TR: 'Bir hata oluştu.', EN: 'An error occurred.' },
  err_update_failed: { TR: 'Kayıt güncellenemedi. Veritabanı izinlerini kontrol edin.', EN: 'Record could not be updated. Check database permissions.' },
  err_password_min_length: { TR: 'Şifre en az 8 karakter olmalıdır.', EN: 'Password must be at least 8 characters.' },
  profile_updated: { TR: 'Profiliniz güncellendi.', EN: 'Profile updated successfully.' },
  cancellation_submitted: { TR: 'İptal talebiniz iletildi.', EN: 'Your cancellation request has been submitted.' },
  appointment_cancelled: { TR: 'Randevunuz iptal edildi.', EN: 'Appointment cancelled.' },
  appointment_success: { TR: 'Randevu talebiniz başarıyla oluşturuldu!', EN: 'Your reservation request was created successfully!' },
  submitting: { TR: 'Gönderiliyor...', EN: 'Submitting...' },
  weekend_restriction: { TR: 'Hafta sonları randevu alınamaz. Lütfen hafta içi bir gün seçin.', EN: 'Appointments cannot be made on weekends. Please select a weekday.' },
  date_restriction: { TR: 'Hafta sonları ve 60 günden ileri tarihler seçilemez.', EN: 'Weekends and dates beyond 60 days are not available.' },
  province_not_found: { TR: 'İl bilgisi bulunamadı.', EN: 'No province information found.' },
  studios_not_found: { TR: 'Bu il için alan bulunamadı.', EN: 'No areas found for this province.' },
  no_timeslots: { TR: 'Bu il için saat dilimi tanımlanmamış.', EN: 'No time slots defined for this province.' },
  back_to_province: { TR: 'İl Seçimine Dön', EN: 'Back to Province Selection' },
  back_to_studio: { TR: 'Alan Seçimine Dön', EN: 'Back to Area Selection' },
  back_to_date: { TR: 'Tarih Seçimine Dön', EN: 'Back to Date Selection' },
  back_to_time: { TR: 'Saat Seçimine Dön', EN: 'Back to Time Selection' },
  province_label: { TR: 'İl', EN: 'Province' },
  studio_label: { TR: 'Alan', EN: 'Area' },
  date_label: { TR: 'Tarih', EN: 'Date' },
  time_label: { TR: 'Saat', EN: 'Time' },
  capacity_label: { TR: 'Kapasite', EN: 'Capacity' },
  capacity_people_label: { TR: 'kişi', EN: 'people' },
  delete_lab_confirm: { TR: 'Bu alanı silmek istediğinizden emin misiniz?', EN: 'Are you sure you want to delete this area?' },
  notif_required_fields: { TR: 'Başlık ve mesaj zorunludur.', EN: 'Title and message are required.' },
  notif_sent: { TR: 'Bildirim gönderildi.', EN: 'Notification sent.' },
  show_password: { TR: 'Şifreyi göster', EN: 'Show password' },
  hide_password: { TR: 'Şifreyi gizle', EN: 'Hide password' },
  btn_yes: { TR: 'Evet', EN: 'Yes' },
  btn_no:  { TR: 'Hayır', EN: 'No' },
  lbl_reg_date: { TR: 'Kayıt Tarihi', EN: 'Registration Date' },
  btn_nevermind: { TR: 'Vazgeç', EN: 'Cancel' },
  processing_please_wait: { TR: 'İşleminiz gerçekleştiriliyor, lütfen bekleyiniz...', EN: 'Processing, please wait...' },
  btn_logout: { TR: 'Çıkış', EN: 'Logout' },
  btn_back: { TR: 'Geri', EN: 'Back' },
  toggle_dark: { TR: 'Karanlık mod', EN: 'Dark mode' },
  prev_month:   { TR: 'Önceki ay', EN: 'Previous month' },
  next_month:   { TR: 'Sonraki ay', EN: 'Next month' },
  toggle_light: { TR: 'Aydınlık mod', EN: 'Light mode' },
  toggle_lang: { TR: 'Dili değiştir', EN: 'Switch language' },
  admin_type_global: { TR: 'Genel Yönetici', EN: 'Global Admin' },
  admin_type_city: { TR: 'İl Yöneticisi', EN: 'Province Admin' },
  btn_refresh: { TR: 'Yenile', EN: 'Refresh' },
  btn_update_password: { TR: 'Şifreyi Güncelle', EN: 'Update Password' },
  btn_save: { TR: 'Kaydet', EN: 'Save' },
  btn_add: { TR: 'Ekle', EN: 'Add' },
  btn_delete: { TR: 'Sil', EN: 'Delete' },
  select_province: { TR: 'İl Seçin', EN: 'Select Province' },
  notif_city_only_hint: { TR: 'Yalnızca seçilen şehrin kullanıcılarına gönderilecek.', EN: 'Will be sent only to users in the selected city.' },
  status_approved: { TR: 'Onaylı', EN: 'Approved' },
  status_pending_approval: { TR: 'Onay Bekliyor', EN: 'Pending Approval' },
  filter_all_provinces: { TR: 'Tüm İller', EN: 'All Provinces' },
  filter_all_locations: { TR: 'Tüm Konumlar', EN: 'All Locations' },
  filter_all_statuses: { TR: 'Tüm Durumlar', EN: 'All Statuses' },
  filter_clear: { TR: 'Filtreleri Temizle', EN: 'Clear Filters' },
  filter_date: { TR: 'Tarih:', EN: 'Date:' },
  filter_date_from: { TR: 'Başlangıç tarihi', EN: 'Start date' },
  filter_date_to: { TR: 'Bitiş tarihi', EN: 'End date' },
  clear: { TR: 'Temizle', EN: 'Clear' },
  tab_appointments_label: { TR: 'Randevular', EN: 'Appointments' },
  tab_studios_label: { TR: 'Alanlar', EN: 'Areas' },
  tab_slots_label: { TR: 'Saat Dilimleri', EN: 'Time Slots' },
  tab_approvals_label: { TR: 'Üye Onayları', EN: 'User Approvals' },
  tab_send_notif: { TR: 'Bildirim Gönder', EN: 'Send Notification' },
  stat_total: { TR: 'Toplam', EN: 'Total' },
  stat_pending_status: { TR: 'Bekleyen Randevu', EN: 'Pending Appts' },
  stat_approved_status: { TR: 'Onaylandı', EN: 'Approved' },
  stat_cancelled_status: { TR: 'İptal', EN: 'Cancelled' },
  search_placeholder: { TR: 'Ad, e-posta, alan ara...', EN: 'Search name, email, area...' },
  search_user_placeholder: { TR: 'İsim veya e-posta ile ara...', EN: 'Search by name or email...' },
  records_count: { TR: 'kayıt', EN: 'records' },
  shown: { TR: 'gösteriliyor', EN: 'shown' },
  show_more: { TR: 'Daha Fazla Göster', EN: 'Show More' },
  remaining: { TR: 'kaldı', EN: 'remaining' },
  lbl_studio: { TR: 'Alan', EN: 'Area' },
  lbl_province: { TR: 'İl', EN: 'Province' },
  lbl_date: { TR: 'Tarih', EN: 'Date' },
  lbl_time: { TR: 'Saat', EN: 'Time' },
  lbl_branch: { TR: 'Branş', EN: 'Branch' },
  lbl_institution: { TR: 'Kurum', EN: 'Institution' },
  lbl_note: { TR: 'Not', EN: 'Note' },
  lbl_status: { TR: 'Durum', EN: 'Status' },
  lbl_created: { TR: 'Oluşturma', EN: 'Created' },
  lbl_action: { TR: 'İşlem', EN: 'Action' },
  audit_detail_city_notifs:  { TR: 'Şehir: {city}', EN: 'City: {city}' },
  audit_detail_all_notifs:   { TR: 'Tüm bildirimler silindi', EN: 'All notifications cleared' },
  audit_detail_force_deleted: { TR: '{name} (zorla silindi)', EN: '{name} (force deleted)' },
  lbl_details: { TR: 'Detay', EN: 'Details' },
  lbl_actor: { TR: 'Yetkili', EN: 'Actor' },
  lbl_size_small:  { TR: 'Küçük', EN: 'Small' },
  lbl_size_medium: { TR: 'Orta', EN: 'Medium' },
  lbl_size_large:  { TR: 'Büyük', EN: 'Large' },
  lbl_size_xlarge: { TR: 'Çok Büyük', EN: 'X-Large' },
  lbl_size_normal: { TR: 'Normal', EN: 'Normal' },
  lbl_font_serif:  { TR: 'Serif (klasik)', EN: 'Serif (classic)' },
  lbl_font_sans:   { TR: 'Sans (modern)', EN: 'Sans (modern)' },
  lbl_align_center: { TR: 'Ortalı', EN: 'Center' },
  lbl_align_left:   { TR: 'Sola Hizalı', EN: 'Left' },
  slot_mgmt_title: { TR: 'Saat Dilimi Yönetimi', EN: 'Time Slot Management' },
  slot_add_new: { TR: 'Yeni Saat Dilimi Ekle', EN: 'Add New Time Slot' },
  slot_none: { TR: 'Henüz saat dilimi eklenmemiş.', EN: 'No time slots added yet.' },
  slot_placeholder: { TR: 'Örn: 09:00 - 10:00', EN: 'E.g.: 09:00 - 10:00' },
  slot_required_fields: { TR: 'Lütfen tüm alanları doldurun.', EN: 'Please fill all fields.' },
  studio_add: { TR: '+ Alan Ekle', EN: '+ Add Area' },
  studio_new: { TR: 'Yeni Alan', EN: 'New Area' },
  studio_edit: { TR: 'Alanı Düzenle', EN: 'Edit Area' },
  studio_city_required: { TR: 'İl ve alan adı zorunludur.', EN: 'Province and area name are required.' },
  studio_name_required: { TR: 'Alan adı zorunludur.', EN: 'Area name is required.' },
  pending_users_title: { TR: 'Onay Bekleyenler', EN: 'Pending Approval' },
  approved_users_title: { TR: 'Onaylı Üyeler', EN: 'Approved Members' },
  no_pending_users: { TR: 'Onay bekleyen kullanıcı yok.', EN: 'No users pending approval.' },
  no_approved_users: { TR: 'Onaylı üye yok.', EN: 'No approved members.' },
  notif_new: { TR: 'Yeni Bildirim Gönder', EN: 'Send New Notification' },
  notif_lbl_type: { TR: 'Tür', EN: 'Type' },
  notif_lbl_title: { TR: 'Başlık', EN: 'Title' },
  notif_lbl_message: { TR: 'Mesaj', EN: 'Message' },
  notif_type_system: { TR: 'Sistem', EN: 'System' },
  notif_type_reminder: { TR: 'Hatırlatma', EN: 'Reminder' },
  notif_type_alert: { TR: 'Uyarı', EN: 'Alert' },
  notif_send_btn: { TR: 'Bildirimi Gönder', EN: 'Send Notification' },
  notif_title_placeholder: { TR: 'Bildirim başlığı...', EN: 'Notification title...' },
  notif_msg_placeholder: { TR: 'Bildirim mesajı...', EN: 'Notification message...' },
  notif_send_email_label: { TR: 'Ayrıca e-posta olarak da gönder', EN: 'Also send as email' },
  notif_email_recipients_count: { TR: '{n} kullanıcıya ulaşacak', EN: 'Will reach {n} users' },
  notif_email_no_recipients: { TR: 'Bu hedef kitle için onaylı kullanıcı yok.', EN: 'No approved users match this audience.' },
  notif_email_result: { TR: 'Bildirim oluşturuldu — {sent} e-posta gönderildi, {failed} başarısız.', EN: 'Notification created — sent {sent} emails, {failed} failed.' },
  notif_email_sending: { TR: 'E-postalar gönderiliyor...', EN: 'Sending emails...' },
  confirm_approve_appt: { TR: 'Bu randevuyu onaylamak istediğinizden emin misiniz?', EN: 'Are you sure you want to approve this appointment?' },
  confirm_cancel_appt: { TR: 'Bu randevuyu iptal etmek istediğinizden emin misiniz?', EN: 'Are you sure you want to cancel this appointment?' },
  confirm_complete_appt: { TR: 'Bu randevuyu tamamlandı olarak işaretlemek istediğinizden emin misiniz?', EN: 'Mark this appointment as completed?' },
  confirm_approve_user: { TR: 'Bu üyeyi onaylamak istediğinizden emin misiniz?', EN: 'Are you sure you want to approve this member?' },
  confirm_revoke_user: { TR: 'Bu üyeyi sistemden silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.', EN: 'Are you sure you want to delete this member? This cannot be undone.' },
  tab_workshops: { TR: 'Atölyeler', EN: 'Workshops' },
  workshop_add: { TR: 'Atölye Ekle', EN: 'Add Workshop' },
  workshop_new: { TR: 'Yeni Atölye', EN: 'New Workshop' },
  workshop_name_label: { TR: 'Atölye Adı', EN: 'Workshop Name' },
  workshop_date_label: { TR: 'Tarih', EN: 'Date' },
  workshop_time_label: { TR: 'Saat', EN: 'Time' },
  workshop_capacity_label: { TR: 'Kapasite', EN: 'Capacity' },
  workshop_location_label: { TR: 'Konum', EN: 'Location' },
  workshop_desc_label: { TR: 'Açıklama', EN: 'Description' },
  workshop_delete_confirm: { TR: 'Bu atölyeyi silmek istediğinizden emin misiniz?', EN: 'Are you sure you want to delete this workshop?' },
  workshop_added: { TR: 'Atölye eklendi.', EN: 'Workshop added.' },
  workshop_name_required: { TR: 'Atölye adı zorunludur.', EN: 'Workshop name is required.' },
  no_workshops: { TR: 'Henüz atölye eklenmemiş.', EN: 'No workshops added yet.' },
  lbl_capacity_slot: { TR: 'Kapasite (slot başına)', EN: 'Capacity (per slot)' },
  lbl_branches: { TR: 'Branşlar', EN: 'Branches' },
  lbl_branches_placeholder: { TR: 'Örn: Fen, Matematik', EN: 'E.g.: Science, Math' },
  province_label_req: { TR: 'İl', EN: 'Province' },
  studio_name_label_req: { TR: 'Alan Adı', EN: 'Area Name' },
  lbl_description: { TR: 'Açıklama', EN: 'Description' },
  lbl_location: { TR: 'Konum', EN: 'Location' },
  lbl_district: { TR: 'İlçe', EN: 'District' },
  btn_edit: { TR: 'Düzenle', EN: 'Edit' },
  btn_retry: { TR: 'Yeniden Dene', EN: 'Retry' },
  lbl_membership_status: { TR: 'Üyelik Durumu', EN: 'Membership Status' },
  btn_approve_member: { TR: 'Üyeliği Onayla', EN: 'Approve Membership' },
  btn_revoke_member: { TR: 'Üyeliği İptal Et', EN: 'Revoke Membership' },
  btn_reject_member: { TR: 'Reddet & Sil', EN: 'Reject & Delete' },
  placeholder_email: { TR: 'E-posta adresiniz', EN: 'Your email address' },
  placeholder_password: { TR: 'Şifreniz', EN: 'Your password' },
  placeholder_registered_email: { TR: 'Kayıtlı e-posta adresiniz', EN: 'Your registered email' },
  notif_appt_approved: { TR: 'Randevunuz Onaylandı', EN: 'Appointment Approved' },
  notif_appt_cancelled: { TR: 'Randevunuz İptal Edildi', EN: 'Appointment Cancelled' },
  loading_signin: { TR: 'Giriş yapılıyor...', EN: 'Signing in...' },
  loading_registering: { TR: 'Kaydediliyor...', EN: 'Registering...' },
  loading_looking_up: { TR: 'Sorgulanıyor...', EN: 'Looking up...' },
  loading_saving: { TR: 'Kaydediliyor...', EN: 'Saving...' },
  upcoming_appointments: { TR: 'Yaklaşan Randevularım', EN: 'Upcoming Appointments' },
  no_upcoming_appointments: { TR: 'Yaklaşan randevu yok.', EN: 'No upcoming appointments.' },
  past_appointments: { TR: 'Geçmiş Randevular', EN: 'Past Appointments' },
  kvkk_title: { TR: 'KVKK Aydınlatma Metni', EN: 'KVKK Information Text' },
  kvkk_consent_suffix: { TR: "'ni okudum ve kabul ediyorum. *", EN: ' — I have read and agree. *' },
  kvkk_agree_btn: { TR: 'Okudum, Onaylıyorum', EN: 'I Read and Agree' },
  btn_close: { TR: 'Kapat', EN: 'Close' },
  btn_ok: { TR: 'Tamam', EN: 'OK' },
  reg_success_title: { TR: 'Başvurunuz Alındı', EN: 'Application Received' },
  reg_success_msg: { TR: 'Üyelik talebiniz alınmıştır. Bilgileriniz kontrol edildikten sonra üyeliğiniz onaylanacaktır.', EN: 'Your membership request has been received. Your membership will be approved after your information is verified.' },
  cancel_modal_title: { TR: 'İptal Talebi', EN: 'Cancellation Request' },
  cancel_modal_subtitle: { TR: 'İptal sebebinizi belirtin (isteğe bağlı).', EN: 'State your cancellation reason (optional).' },
  cancel_reason_placeholder: { TR: 'İptal sebebinizi yazın...', EN: 'Write your reason...' },
  btn_submit: { TR: 'Gönder', EN: 'Submit' },
  lbl_cancel_reason: { TR: 'İptal notu', EN: 'Cancel reason' },
  btn_request_cancellation: { TR: 'İptal Talebi Gönder', EN: 'Request Cancellation' },
  data_load_failed: { TR: 'Veriler yüklenemedi.', EN: 'Failed to load data.' },
  realtime_error:   { TR: 'Gerçek zamanlı bağlantı kurulamadı. Veriler otomatik güncellenmeyebilir.', EN: 'Real-time connection lost. Data may not update automatically.' },
  clear_notifications_confirm: { TR: 'Tüm bildirimler kalıcı olarak silinecek. Emin misiniz?', EN: 'All notifications will be permanently deleted. Are you sure?' },
  menu_open: { TR: 'Menüyü aç', EN: 'Open menu' },
  menu_close: { TR: 'Menüyü kapat', EN: 'Close menu' },
  pw_requirement_hint: { TR: '(Şifreniz en az 8 karakter, büyük/küçük harf, rakam ve özel karakter içermelidir. Örnek: !, @, #, $, %)', EN: '(Password must be at least 8 characters and include uppercase, lowercase, a number and a special character. E.g.: !, @, #, $, %)' },
  pw_req_length: { TR: 'En az 8 karakter', EN: 'At least 8 characters' },
  pw_req_upper: { TR: 'Büyük harf (A-Z)', EN: 'Uppercase letter (A-Z)' },
  pw_req_lower: { TR: 'Küçük harf (a-z)', EN: 'Lowercase letter (a-z)' },
  pw_req_number: { TR: 'Rakam (0-9)', EN: 'Number (0-9)' },
  pw_req_special: { TR: 'Özel karakter (!, @, #, $, %)', EN: 'Special character (!, @, #, $, %)' },
  err_password_weak: { TR: 'Şifreniz en az 8 karakter, büyük/küçük harf, rakam ve özel karakter içermelidir.', EN: 'Password must contain at least 8 characters, uppercase/lowercase letters, a number and a special character.' },
  btn_reset_password: { TR: 'Şifre Sıfırla', EN: 'Reset Password' },
  reset_pw_title: { TR: 'Şifre Sıfırla', EN: 'Reset Password' },
  reset_pw_success: { TR: 'Şifre başarıyla sıfırlandı.', EN: 'Password reset successfully.' },
  tab_admins: { TR: 'Yöneticiler', EN: 'Admins' },
  tab_audit: { TR: 'Denetim', EN: 'Audit' },
  admin_add: { TR: '+ Yönetici Ekle', EN: '+ Add Admin' },
  admin_new: { TR: 'Yeni Yönetici', EN: 'New Admin' },
  admin_delete_confirm: { TR: 'Bu yöneticiyi silmek istediğinizden emin misiniz?', EN: 'Are you sure you want to delete this admin?' },
  admin_added: { TR: 'Yönetici eklendi.', EN: 'Admin added.' },
  admin_search_placeholder: { TR: 'İsim veya e-posta ara...', EN: 'Search by name or email...' },
  lbl_role: { TR: 'Rol', EN: 'Role' },
  lbl_phone: { TR: 'Telefon', EN: 'Phone' },
  err_admin_required_fields: { TR: 'İsim, e-posta ve şifre zorunludur.', EN: 'Name, email and password are required.' },
  err_city_required: { TR: 'İl yöneticisi için il seçimi zorunludur.', EN: 'Province selection is required for province admin.' },
  no_admins: { TR: 'Yönetici bulunamadı.', EN: 'No admins found.' },
  approve_cancellation: { TR: 'İptali Onayla', EN: 'Approve Cancellation' },
  deny_cancellation: { TR: 'Talebi Reddet', EN: 'Deny Request' },
  confirm_approve_cancellation: { TR: 'Kullanıcının iptal talebini onaylayıp randevuyu iptal etmek istediğinizden emin misiniz?', EN: 'Approve the cancellation request and cancel the appointment?' },
  confirm_deny_cancellation: { TR: 'İptal talebini reddetmek istediğinizden emin misiniz? Randevu "Onaylı" durumuna döner.', EN: 'Deny this cancellation request? The appointment will return to Approved.' },
  action_success_approved: { TR: 'Randevu onaylandı.', EN: 'Appointment approved.' },
  action_success_cancelled: { TR: 'Randevu iptal edildi.', EN: 'Appointment cancelled.' },
  action_success_completed: { TR: 'Randevu tamamlandı olarak işaretlendi.', EN: 'Appointment marked as completed.' },
  action_success_cancellation_approved: { TR: 'İptal talebi onaylandı.', EN: 'Cancellation approved.' },
  action_success_cancellation_denied: { TR: 'İptal talebi reddedildi.', EN: 'Cancellation denied.' },
  // Session timeout
  session_timeout_title: { TR: 'Oturum Zaman Aşımı', EN: 'Session Timeout' },
  session_timeout_msg: { TR: 'Uzun süre işlem yapmadınız. {t} saniye sonra otomatik çıkış yapılacak.', EN: 'You have been inactive. Auto-logout in {t} seconds.' },
  session_continue: { TR: 'Devam Et', EN: 'Stay Logged In' },
  // Notification search
  notif_search_placeholder: { TR: 'Bildirim ara...', EN: 'Search notifications...' },
  // Audit search
  audit_search_placeholder: { TR: 'Kişi, e-posta veya detay ara...', EN: 'Search by person, email or detail...' },
  // Cancellation reason label (admin view)
  lbl_cancellation_reason: { TR: 'İptal Sebebi', EN: 'Cancellation Reason' },
  // Bulk operations
  bulk_approve: { TR: 'Seçilenleri Onayla', EN: 'Approve Selected' },
  bulk_cancel: { TR: 'Seçilenleri İptal Et', EN: 'Cancel Selected' },
  bulk_selected: { TR: '{n} seçili', EN: '{n} selected' },
  bulk_deselect: { TR: 'Seçimi Kaldır', EN: 'Deselect All' },
  bulk_select_all: { TR: 'Tümünü seç', EN: 'Select all' },
  bulk_select_one: { TR: 'Seç:', EN: 'Select:' },
  // Calendar view
  view_calendar: { TR: 'Takvim', EN: 'Calendar' },
  view_list: { TR: 'Liste', EN: 'List' },
  // Workshop registration
  workshop_register: { TR: 'Kayıt Ol', EN: 'Register' },
  workshop_unregister: { TR: 'Kaydı İptal Et', EN: 'Unregister' },
  workshop_registered_badge: { TR: 'Kayıtlısınız', EN: 'Registered' },
  workshop_full: { TR: 'Kontenjan Dolu', EN: 'Workshop Full' },
  workshop_register_success: { TR: 'Atölye kaydınız oluşturuldu.', EN: 'Workshop registration successful.' },
  workshop_unregister_success: { TR: 'Atölye kaydınız iptal edildi.', EN: 'Workshop registration cancelled.' },
  workshop_registrants_title: { TR: 'Kayıtlılar', EN: 'Registrants' },
  workshop_no_registrants: { TR: 'Henüz kayıtlı yok.', EN: 'No registrants yet.' },
  err_workshop_full: { TR: 'Atölye kapasitesi dolu.', EN: 'Workshop is at full capacity.' },
  err_already_registered: { TR: 'Bu atölye için zaten kayıtlısınız.', EN: 'You are already registered for this workshop.' },
  // City change in profile
  city_change_note: { TR: 'Şehir değişikliği aktif randevularınızı etkilemez.', EN: 'City change does not affect existing appointments.' },
  // Messaging
  tab_messages:           { TR: 'Mesajlar',                    EN: 'Messages' },
  msg_to_city_admin:      { TR: 'İl Yöneticisi',              EN: 'City Admin' },
  msg_to_global_admin:    { TR: 'Genel Yönetici',             EN: 'Global Admin' },
  msg_no_conversations:   { TR: 'Henüz mesaj yok.',           EN: 'No messages yet.' },
  msg_no_messages:        { TR: 'Mesaj gönder.',              EN: 'Send a message.' },
  msg_placeholder:        { TR: 'Mesajınızı yazın...',        EN: 'Type your message...' },
  msg_send:               { TR: 'Gönder',                     EN: 'Send' },
  msg_from_user:          { TR: 'Kullanıcıdan',               EN: 'From user' },
  msg_conversations_title: { TR: 'Konuşmalar',               EN: 'Conversations' },
  msg_all_cities:         { TR: 'Tüm İller',                  EN: 'All Provinces' },
  msg_user_to_city:       { TR: 'Kullanıcı → İl',            EN: 'User → City' },
  msg_city_to_global:     { TR: 'İl → Genel',                EN: 'City → Global' },
  msg_user_to_global:     { TR: 'Kullanıcı → Genel',         EN: 'User → Global' },
  msg_unread_badge:       { TR: 'okunmamış',                  EN: 'unread' },
  msg_new_message_notif:  { TR: 'Yeni mesajınız var.',        EN: 'You have a new message.' },
  // Closed days
  tab_closed_days:      { TR: 'Kapalı Günler',              EN: 'Closed Days' },
  closed_day_add:       { TR: 'Kapalı Gün Ekle',            EN: 'Add Closed Day' },
  closed_day_reason:    { TR: 'Sebep (opsiyonel)',           EN: 'Reason (optional)' },
  closed_day_added:     { TR: 'Kapalı gün eklendi.',         EN: 'Closed day added.' },
  closed_day_deleted:   { TR: 'Kapalı gün silindi.',         EN: 'Closed day removed.' },
  no_closed_days:       { TR: 'Kapalı gün yok.',             EN: 'No closed days.' },
  err_date_closed:      { TR: 'Bu tarih kapalı olarak işaretlenmiş.', EN: 'This date is closed.' },
  err_date_holiday:     { TR: 'Bu tarih resmi tatildir.',    EN: 'This is a public holiday.' },
  err_sunday:           { TR: 'Pazar günleri randevu alınamaz.', EN: 'Appointments cannot be made on Sundays.' },
  lbl_holiday:          { TR: 'Resmi Tatil',                 EN: 'Public Holiday' },
  today_bookings_badge: { TR: 'bugün aktif',                 EN: 'active today' },
  // Email broadcast tab
  tab_email:              { TR: 'E-posta Gönder',            EN: 'Send Email' },
  email_subject:          { TR: 'Konu',                      EN: 'Subject' },
  email_subject_ph:       { TR: 'E-posta konusu...',         EN: 'Email subject...' },
  email_body:             { TR: 'İçerik',                    EN: 'Body' },
  email_body_ph:          { TR: 'E-posta içeriği...',        EN: 'Email body...' },
  email_recipients_users: { TR: 'Kullanıcılar',             EN: 'Users' },
  email_recipients_admins:{ TR: 'Yöneticiler',              EN: 'Admins' },
  email_send_users:       { TR: 'Kullanıcılara Gönder',     EN: 'Send to Users' },
  email_send_admins:      { TR: 'Yöneticilere Gönder',      EN: 'Send to Admins' },
  email_select_all:       { TR: 'Tümünü Seç',               EN: 'Select All' },
  email_deselect_all:     { TR: 'Seçimi Kaldır',            EN: 'Deselect All' },
  email_search_ph:        { TR: 'İsim veya e-posta ara...',  EN: 'Search by name or email...' },
  email_no_match:         { TR: 'Eşleşen kayıt yok.',       EN: 'No matching records.' },
  email_sending:          { TR: 'Gönderiliyor...',           EN: 'Sending...' },
  email_sent_ok:          { TR: '{n} alıcıya başarıyla gönderildi.', EN: 'Successfully sent to {n} recipients.' },
  email_sent_partial:     { TR: '{sent}/{total} alıcıya gönderildi ({failed} başarısız).', EN: 'Sent to {sent}/{total} recipients ({failed} failed).' },
  email_err_no_recipients:{ TR: 'Lütfen en az bir alıcı seçin.',   EN: 'Please select at least one recipient.' },
  email_err_subject:      { TR: 'Konu ve içerik zorunludur.',       EN: 'Subject and body are required.' },
  email_err_send:         { TR: 'Gönderme başarısız oldu.',         EN: 'Failed to send email.' },
  email_selected_n:       { TR: '{n} seçili',                       EN: '{n} selected' },
  // Waitlist
  waitlist_added:         { TR: 'Bekleme listesine eklendiniz. Yer açıldığında bildirim alacaksınız.', EN: 'Added to waitlist. You will be notified when a slot opens.' },
  waitlist_removed:       { TR: 'Bekleme listesinden çıkarıldınız.', EN: 'Removed from waitlist.' },
  waitlist_join:          { TR: 'Bekleme Listesine Ekle', EN: 'Join Waitlist' },
  waitlist_on_list:       { TR: '✓ Bekleme Listesinde', EN: '✓ On Waitlist' },
  // Admin management
  admin_cannot_delete_self: { TR: 'Kendi hesabınızı silemezsiniz.', EN: 'You cannot delete your own account.' },
  admin_self_indicator:   { TR: '(siz)', EN: '(you)' },
  admin_edit_title:       { TR: 'Yönetici Düzenle', EN: 'Edit Admin' },
  admin_edit_role_warning: { TR: '⚠️ Rol değişiyor: {from} → {to}. Kaydet\'e basarak onaylıyorsunuz.', EN: '⚠️ Role will change: {from} → {to}. Saving confirms this change.' },
  // Workshop admin
  workshop_edit_title:    { TR: 'Atölyeyi Düzenle', EN: 'Edit Workshop' },
  workshop_attendance_attended: { TR: 'Katıldı', EN: 'Attended' },
  workshop_attendance_not_yet: { TR: 'Katılmadı', EN: 'Not yet' },
  workshop_remove_reg:    { TR: 'Kaydı Sil', EN: 'Remove Registration' },
  // Time slots validation
  slot_invalid_format:    { TR: 'Geçersiz format. Örn: 09:00 - 17:00', EN: 'Invalid format. E.g.: 09:00 - 17:00' },
  slot_start_before_end:  { TR: 'Başlangıç saati bitiş saatinden önce olmalıdır.', EN: 'Start time must be before end time.' },
  slot_already_exists:    { TR: 'Bu saat dilimi zaten mevcut.', EN: 'This time slot already exists.' },
  // Notifications admin tab
  notif_history_title:    { TR: 'Bildirim Geçmişi', EN: 'Notification History' },
  notif_history_empty:    { TR: 'Bildirim bulunamadı.', EN: 'No notifications found.' },
  // Appointments admin edit
  appt_edit_datetime:     { TR: 'Tarih / Saat Değiştir', EN: 'Change Date / Time' },
  appt_edit_current:      { TR: 'mevcut', EN: 'current' },
  // User approvals tab
  err_add_user_required_fields: { TR: 'Ad, soyad, e-posta, şifre ve il zorunludur.', EN: 'Name, surname, email, password and province are required.' },
  user_added:             { TR: 'Üye eklendi.', EN: 'Member added.' },
  csv_import:             { TR: 'CSV İçe Aktar', EN: 'Import CSV' },
  btn_add_member:         { TR: 'Üye Ekle', EN: 'Add Member' },
  csv_import_result:      { TR: '{ok} eklendi, {fail} başarısız', EN: '{ok} added, {fail} failed' },
  csv_errors_more:        { TR: '... ve {n} daha', EN: '... and {n} more' },
  csv_import_pw_hint:     { TR: 'Her kullanıcıya benzersiz geçici şifre atanır. Kullanıcılar ilk girişte şifre değiştirmek zorunda kalacak.', EN: 'Each user gets a unique temporary password. Users will be forced to change it on first login.' },
  csv_err_missing_field:  { TR: 'Satır {n}: eksik alan', EN: 'Row {n}: missing field' },
  csv_err_invalid_email:  { TR: 'Satır {n}: geçersiz e-posta ({email})', EN: 'Row {n}: invalid email ({email})' },
  csv_err_city_not_found: { TR: 'Satır {n}: il bulunamadı ({city})', EN: 'Row {n}: city not found ({city})' },
  csv_err_row_generic:    { TR: 'Satır {n} ({email}): {error}', EN: 'Row {n} ({email}): {error}' },
  csv_err_read_file:      { TR: 'Dosya okunamadı.', EN: 'Could not read file.' },
  csv_err_already_exists: { TR: 'Satır {n} ({email}): bu e-posta zaten kayıtlı', EN: 'Row {n} ({email}): email already registered' },
  user_new:               { TR: 'Yeni Üye', EN: 'New Member' },
  lbl_password_required:  { TR: 'Şifre *', EN: 'Password *' },
  lbl_confirm_password_required: { TR: 'Şifre Tekrar *', EN: 'Confirm Password *' },
  add_user_pw_hint:       { TR: 'Kullanıcı ilk girişte bu şifreyi değiştirmek zorunda kalacak.', EN: 'User will be required to change this password on first login.' },
  copy_pw_modal_title:    { TR: 'Geçici Şifre', EN: 'Temporary Password' },
  copy_pw_modal_desc:     { TR: 'Bu geçici şifreyi güvenli bir şekilde kullanıcıyla paylaşın. Pencere kapatıldıktan sonra tekrar görüntülenemez.', EN: 'Share this temporary password securely with the user. It cannot be viewed again after closing.' },
  copy_pw_btn_copy:       { TR: 'Kopyala', EN: 'Copy' },
  copy_pw_btn_copied:     { TR: 'Kopyalandı!', EN: 'Copied!' },
  copy_pw_done_btn:       { TR: 'Tamam, Kaydettim', EN: 'Done, Saved It' },
  email_p_credentials_shared: { TR: 'Giriş bilgileriniz yöneticiniz tarafından güvenli bir şekilde iletilecektir.', EN: 'Your login credentials will be securely provided by your administrator.' },
  select_all:             { TR: 'Tümünü Seç', EN: 'Select All' },
  approve_selected_n:     { TR: 'Seçilenleri Onayla ({n})', EN: 'Approve Selected ({n})' },
  err_bulk_approve_failed:{ TR: '{n} üye onaylanamadı.', EN: '{n} users could not be approved.' },
  confirm_bulk_approve:   { TR: '{n} üyeyi onaylamak istediğinizden emin misiniz?', EN: 'Approve {n} selected member(s)?' },
  active_appts_will_cancel: { TR: 'aktif randevu iptal edilecek', EN: 'active appointment(s) will be cancelled' },
  // General UI
  loading:                    { TR: 'Yükleniyor...', EN: 'Loading...' },
  btn_update:                 { TR: 'Güncelle', EN: 'Update' },
  btn_continue:               { TR: 'Devam Et', EN: 'Continue' },
  btn_remove:                 { TR: 'Çıkar', EN: 'Remove' },
  btn_yes_remove:             { TR: 'Evet, Çıkar', EN: 'Yes, Remove' },
  btn_sign_out:               { TR: 'Çıkış Yap', EN: 'Sign Out' },
  btn_choose_file:            { TR: 'Dosya Seç', EN: 'Choose File' },
  photo_hint:                 { TR: 'Fotoğraf: JPEG, PNG, WebP veya GIF · Maks. 1 MB', EN: 'Photo: JPEG, PNG, WebP or GIF · Max 1 MB' },
  photo_hint_extended:        { TR: 'Fotoğraf: JPEG, PNG, WebP, GIF · Maks. 1 MB', EN: 'Photo: JPEG, PNG, WebP, GIF · Max 1 MB' },
  avatar_upload_hint:         { TR: 'JPEG, PNG, WebP veya GIF · Maks. 1 MB', EN: 'JPEG, PNG, WebP or GIF · Max 1 MB' },
  alt_profile_photo:          { TR: 'profil fotoğrafı', EN: 'profile photo' },
  lbl_full_name:              { TR: 'Ad Soyad', EN: 'Full Name' },
  err_invalid_email:          { TR: 'Geçerli bir e-posta adresi girin.', EN: 'Enter a valid email address.' },
  err_phone_format:           { TR: 'Geçerli bir telefon numarası girin. Örnek: 05XX XXX XX XX', EN: 'Enter a valid phone number. Example: 05XX XXX XX XX' },
  tab_certificate:            { TR: 'Sertifika', EN: 'Certificate' },
  location_placeholder:       { TR: 'Konum (isteğe bağlı), örn: Gölbaşı BİLSEM', EN: 'Location (optional), e.g.: Gölbaşı BİLSEM' },
  lbl_size_small:             { TR: 'Küçük', EN: 'Small' },
  lbl_size_medium:            { TR: 'Orta', EN: 'Medium' },
  lbl_size_large:             { TR: 'Büyük', EN: 'Large' },
  lbl_size_xlarge:            { TR: 'Çok Büyük', EN: 'X-Large' },
  // Profile screen
  appt_rescheduled:           { TR: 'Randevu yeniden zamanlandı.', EN: 'Appointment rescheduled.' },
  pending_cancellation_title: { TR: 'Bekleyen İptal Talepleriniz', EN: 'Pending Cancellation Requests' },
  waiting_admin_review:       { TR: 'Yönetici onayı bekleniyor.', EN: 'Waiting for admin review.' },
  no_appts_on_date:           { TR: 'Bu tarihte randevu yok.', EN: 'No appointments on this date.' },
  appts_cancelled_n:          { TR: 'İptal Edilmiş ({n})', EN: 'Cancelled ({n})' },
  waitlist_title_n:           { TR: 'Bekleme Listesi ({n})', EN: 'Waitlist ({n})' },
  my_workshop_regs_n:         { TR: 'Atölye Kayıtlarım ({n})', EN: 'My Workshop Registrations ({n})' },
  workshop_date_tbd:          { TR: 'Tarih belirlenmedi', EN: 'Date TBD' },
  my_certificates_n:          { TR: 'Sertifikalarım ({n})', EN: 'My Certificates ({n})' },
  reschedule_title:           { TR: 'Yeniden Zamanla', EN: 'Reschedule' },
  reschedule_step1:           { TR: '1. Yeni Tarih Seçin', EN: '1. Pick a New Date' },
  reschedule_step2:           { TR: '2. Saat Seçin', EN: '2. Pick a Time' },
  slot_free_count:            { TR: 'boş', EN: 'free' },
  city_change_title:          { TR: 'Şehir Değişikliği', EN: 'City Change' },
  city_change_warning:        { TR: 'Aktif randevularınız var. Şehri değiştirirseniz mevcut randevularınız etkilenmez ancak yeni şehirde oluşturmanız gerekebilir. Devam etmek istiyor musunuz?', EN: 'You have active appointments. Changing city will not cancel them but new appointments must be in the new city. Do you want to continue?' },
  waitlist_remove_title:      { TR: 'Bekleme Listesinden Çıkar', EN: 'Remove from Waitlist' },
  waitlist_remove_confirm:    { TR: 'Bu bekleme listesi kaydını silmek istediğinizden emin misiniz?', EN: 'Are you sure you want to remove this waitlist entry?' },
  // Force password change
  force_pw_title:             { TR: 'Şifrenizi Değiştirin', EN: 'Change Your Password' },
  force_pw_subtitle:          { TR: 'Yöneticiniz şifrenizi sıfırladı. Devam edebilmek için yeni bir şifre belirlemeniz gerekiyor.', EN: 'Your admin has reset your password. You must set a new password to continue.' },
  lbl_temp_password:          { TR: 'Geçici Şifre (Admin Tarafından Verilen)', EN: 'Temporary Password (Given by Admin)' },
  // Notification center
  notif_filter_all_types:     { TR: 'Tüm Türler', EN: 'All Types' },
  notif_type_appointment:     { TR: 'Randevu', EN: 'Appointment' },
  clear_notif_city_confirm:   { TR: 'Yalnızca "{city}" iline ait bildirimler kalıcı olarak silinecek. Emin misiniz?', EN: 'Only notifications for "{city}" will be permanently deleted. Are you sure?' },
  // Workshops screen
  view_certificate:           { TR: 'Sertifikamı Görüntüle', EN: 'View My Certificate' },
  awaiting_attendance:        { TR: 'Katılım onayı bekleniyor…', EN: 'Awaiting attendance confirmation…' },
  upcoming_workshops:         { TR: 'Yaklaşan Atölyeler', EN: 'Upcoming Workshops' },
  past_workshops:             { TR: 'Geçmiş Atölyeler', EN: 'Past Workshops' },
  // Messages screen
  err_conv_start:             { TR: 'Konuşma başlatılamadı. Lütfen tekrar deneyin.', EN: 'Could not start conversation. Please try again.' },
  err_msgs_load:              { TR: 'Mesajlar yüklenemedi. Lütfen tekrar deneyin.', EN: 'Failed to load messages. Please try again.' },
  err_msg_send:               { TR: 'Mesaj gönderilemedi.', EN: 'Failed to send message.' },
  // Location slot section
  slot_time_required:         { TR: 'Saat dilimi gereklidir.', EN: 'Time slot is required.' },
  slot_no_slots_yet:          { TR: 'Henüz saat dilimi eklenmedi.', EN: 'No time slots yet.' },
  // Closed days tab
  closed_day_already_exists:  { TR: 'Bu tarih zaten kapalı olarak işaretlenmiş.', EN: 'This date is already marked as closed.' },
  closed_days_auto_note:      { TR: 'Pazar günleri ve resmi tatiller otomatik olarak kapalıdır. Aşağıdan ek kapalı günler ekleyebilirsiniz.', EN: 'Sundays and public holidays are automatically closed. You can add additional closed days below.' },
  lbl_date_required:          { TR: 'Tarih *', EN: 'Date *' },
  closed_day_reason_ph:       { TR: 'Tatil, bakım...', EN: 'Holiday, maintenance...' },
  all_provinces_global:       { TR: 'Tüm İller (global)', EN: 'All Provinces (global)' },
  // Certificates tab
  err_logo_too_large:         { TR: "Logo dosyası 2 MB'dan büyük olamaz.", EN: 'Logo file must be under 2 MB.' },
  cert_default_title:         { TR: 'KATILIM SERTİFİKASI', EN: 'CERTIFICATE OF ATTENDANCE' },
  cert_default_body:          { TR: '{{tarih}} tarihinde {{konum}} adresinde gerçekleştirilen "{{atolye}}" atölyesine katıldığınız için bu belgeyi almaya hak kazandınız.', EN: 'This certificate is awarded for attending the "{{atolye}}" workshop held at {{konum}} on {{tarih}}.' },
  err_cert_required:          { TR: 'Başlık, kurum ve metin zorunludur.', EN: 'Title, institution, and body text are required.' },
  cert_template_saved:        { TR: 'Şablon kaydedildi.', EN: 'Template saved.' },
  cert_email_confirm:         { TR: '"{workshop}" atölyesindeki {count} katılımcıya sertifika e-postası gönderilecek. Onaylıyor musunuz?', EN: 'Send certificate email to {count} attendee(s) of "{workshop}"?' },
  cert_template_title:        { TR: 'Sertifika Şablonu', EN: 'Certificate Template' },
  cert_show_form:             { TR: 'Formu Göster', EN: 'Show Form' },
  cert_preview:               { TR: 'Önizleme', EN: 'Preview' },
  cert_vars_hint:             { TR: 'Değişkenler: {{katilimci}} · katılımcı adı, {{atolye}} · atölye adı, {{tarih}} · tarih, {{konum}} · yer', EN: 'Variables: {{katilimci}} · participant name, {{atolye}} · workshop name, {{tarih}} · date, {{konum}} · location' },
  lbl_logo_optional:          { TR: 'Logo (isteğe bağlı)', EN: 'Logo (optional)' },
  url_placeholder:            { TR: 'https://...', EN: 'https://...' },
  logo_upload_hint:           { TR: 'Maks. 2 MB · URL veya dosya yükle', EN: 'Max 2 MB · Enter URL or upload file' },
  alt_cert_logo:              { TR: 'Sertifika logosu', EN: 'Certificate logo' },
  lbl_logo_size:              { TR: 'Logo Boyutu', EN: 'Logo Size' },
  lbl_institution_name:       { TR: 'Kurum Adı', EN: 'Institution Name' },
  placeholder_multiline:      { TR: 'Alt satır için Enter kullanın', EN: 'Press Enter for a new line' },
  lbl_cert_title:             { TR: 'Sertifika Başlığı', EN: 'Certificate Title' },
  lbl_title_size:             { TR: 'Başlık Punto', EN: 'Title Size' },
  lbl_cert_body:              { TR: 'Sertifika Metni', EN: 'Certificate Body Text' },
  lbl_body_size:              { TR: 'Metin Punto', EN: 'Body Size' },
  lbl_alignment:              { TR: 'Hizalama', EN: 'Alignment' },
  lbl_name_font:              { TR: 'İsim Fontu', EN: 'Name Font' },
  lbl_signatory_name:         { TR: 'İmzalayan Adı', EN: 'Signatory Name' },
  lbl_signatory_title:        { TR: 'Unvan', EN: 'Title' },
  lbl_footer_optional:        { TR: 'Alt Metin (isteğe bağlı)', EN: 'Footer (optional)' },
  btn_save_template:          { TR: 'Şablonu Kaydet', EN: 'Save Template' },
  cert_email_section:         { TR: 'Sertifika E-postası Gönder', EN: 'Send Certificate Email' },
  cert_email_desc:            { TR: 'Seçili atölyeye katılmış (attended) kullanıcılara sertifika hazır bildirimi gönderir.', EN: 'Sends a certificate-ready notification to all users marked as attended for the selected workshop.' },
  select_workshop:            { TR: 'Atölye Seçin', EN: 'Select Workshop' },
  cert_attendee_count:        { TR: 'Katılımcı: {n} kişi', EN: 'Attendees: {n}' },
  cert_emails_sent:           { TR: '{sent}/{total} e-posta gönderildi', EN: '{sent}/{total} emails sent' },
  // Stats tab
  btn_print_pdf:          { TR: 'Yazdır / PDF', EN: 'Print / PDF' },
  show_less:              { TR: 'Daha az', EN: 'Show less' },
  show_all_n:             { TR: 'Tümünü gör ({n})', EN: 'Show all ({n})' },
  stats_top_users:        { TR: 'En Çok Randevu Alan Kullanıcılar', EN: 'Top Booking Users' },
  stat_upcoming:          { TR: 'Yaklaşan', EN: 'Upcoming' },
  stat_past:              { TR: 'Geçmiş', EN: 'Past' },
  stat_no_date:           { TR: 'Tarifsiz', EN: 'No Date' },
  // Workshop admin tab
  workshop_updated:           { TR: 'Atölye güncellendi.', EN: 'Workshop updated.' },
  workshop_delete_suffix:     { TR: 'kayıtlı katılımcı silinecek', EN: 'registered participants will be removed' },
  err_time_range_invalid:     { TR: 'Saat formatı geçersiz veya bitiş saati başlangıçtan önce. Örnek: 09:00 - 17:00', EN: 'Invalid time format or end time is before start. Example: 09:00 - 17:00' },
  err_capacity_min:           { TR: 'Kapasite en az 1 olmalıdır.', EN: 'Capacity must be at least 1.' },
  err_capacity_min_n:         { TR: 'Kapasite en az {n} olmalıdır ({n} kayıtlı katılımcı var).', EN: 'Capacity must be at least {n} ({n} already registered).' },
  lbl_general:                { TR: 'Genel', EN: 'General' },
  // AuditTab
  lbl_audit_log:              { TR: 'Denetim Kaydı', EN: 'Audit Log' },
  err_load_audit:             { TR: 'Denetim kayıtları yüklenemedi. Sayfayı yenileyin.', EN: 'Failed to load audit logs. Please refresh.' },
  filter_all_actions:         { TR: 'Tüm İşlemler', EN: 'All Actions' },
  lbl_date_colon:             { TR: 'Tarih:', EN: 'Date:' },
  btn_clear:                  { TR: 'Temizle', EN: 'Clear' },
  no_records_found:           { TR: 'Kayıt bulunamadı.', EN: 'No records found.' },
  // StudiosTab
  record_added:               { TR: 'Kayıt eklendi.', EN: 'Record added.' },
  record_updated:             { TR: 'Kayıt güncellendi.', EN: 'Record updated.' },
  btn_fix_data:               { TR: 'Veriyi Düzenle', EN: 'Fix Data' },
  migration_confirm:          { TR: 'Veri göçü geri alınamaz. Devam etmek istiyor musunuz?', EN: 'Data migration cannot be undone. Continue?' },
  migration_completed_errors: { TR: 'Göç tamamlandı ancak {n} kayıtta hata oluştu.', EN: 'Migration completed with {n} error(s).' },
  // AdminManagementTab
  lbl_edit_role_province:     { TR: 'Rol / İl Düzenle', EN: 'Edit Role / Province' },
  // AppointmentsTab
  btn_change_datetime:        { TR: 'Tarih/Saat Değiştir', EN: 'Change Date/Time' },
  // UserReservationScreen
  confirm_appointment_title:  { TR: 'Randevuyu Onayla', EN: 'Confirm Appointment' },
  btn_confirm:                { TR: 'Onayla', EN: 'Confirm' },
  btn_go_back:                { TR: 'Geri Dön', EN: 'Go Back' },
  // CertificateModal
  cert_greeting:              { TR: 'Sayın', EN: 'This certifies that' },
  // MainAppContainer
  notif_unread_count:         { TR: '{n} okunmamış bildirim', EN: '{n} unread notifications' },
  // AppContext - error messages
  err_file_too_large:         { TR: 'Dosya 1 MB\'dan büyük olamaz.', EN: 'File must be under 1 MB.' },
  err_file_type:              { TR: 'Yalnızca JPEG, PNG, WebP veya GIF yükleyebilirsiniz.', EN: 'Only JPEG, PNG, WebP or GIF allowed.' },
  err_slot_full:              { TR: 'Bu slot dolu.', EN: 'This slot is full.' },
  err_already_on_waitlist:    { TR: 'Zaten bekleme listelesindesiniz.', EN: 'Already on the waitlist.' },
  // Notification titles
  notif_reminder_title:           { TR: 'Yaklaşan Randevu Hatırlatması', EN: 'Upcoming Appointment Reminder' },
  notif_new_member_title:         { TR: 'Yeni Üye Başvurusu', EN: 'New Member Request' },
  notif_appt_approved_title:      { TR: 'Randevu Onaylandı', EN: 'Appointment Approved' },
  notif_appt_cancelled_title:     { TR: 'Randevu İptal Edildi', EN: 'Appointment Cancelled' },
  notif_cancel_requested_title:   { TR: 'Randevu İptal Talebi', EN: 'Appointment Cancellation Request' },
  notif_cancellation_denied_title:{ TR: 'İptal Talebi Reddedildi', EN: 'Cancellation Request Denied' },
  notif_membership_approved_title:{ TR: 'Üyelik Onaylandı', EN: 'Membership Approved' },
  notif_admin_added_title:        { TR: 'Yeni Yönetici Eklendi', EN: 'New Admin Added' },
  notif_admin_pw_reset_title:     { TR: 'Yönetici Şifresi Sıfırlandı', EN: 'Admin Password Reset' },
  notif_appt_rescheduled_title:   { TR: 'Randevu Yeniden Planlandı', EN: 'Appointment Rescheduled' },
  notif_waitlist_available_title: { TR: 'Bekleme Listesi: Slot Açıldı', EN: 'Waitlist: Slot Available' },
  // Notification messages
  notif_reminder_msg:             { TR: '{lab} - {date} {slot} tarihli randevunuz yaklaşıyor.', EN: 'Your appointment at {lab} on {date} {slot} is coming up.' },
  notif_new_member_msg:           { TR: '{name} ({email}) kayıt talebinde bulundu.', EN: '{name} ({email}) has submitted a registration request.' },
  notif_appt_approved_msg:        { TR: '{teacher} adlı öğretmenin {lab} için {date} tarihli randevusu onaylandı.', EN: '{teacher}\'s appointment for {lab} on {date} was approved.' },
  notif_appt_cancelled_admin_msg: { TR: '{teacher} adlı öğretmenin {lab} için {date} tarihli randevusu iptal edildi.', EN: '{teacher}\'s appointment for {lab} on {date} was cancelled.' },
  notif_appt_cancelled_user_msg:  { TR: '{teacher} adlı öğretmen, {lab} için {date} tarihli bekleyen randevusunu iptal etti.', EN: '{teacher} cancelled their pending appointment for {lab} on {date}.' },
  notif_cancel_requested_msg:     { TR: '{teacher} adlı öğretmen, {lab} için {date} tarihli randevusunu iptal talep etti.', EN: '{teacher} requested cancellation of their {lab} appointment on {date}.' },
  notif_cancellation_denied_msg:  { TR: '{teacher} adlı öğretmenin {lab} için {date} tarihli iptal talebi reddedildi.', EN: '{teacher}\'s cancellation request for {lab} on {date} was denied.' },
  notif_membership_approved_msg:  { TR: '{name} adlı öğretmenin üyeliği onaylandı.', EN: '{name}\'s membership has been approved.' },
  notif_admin_added_msg:          { TR: '{name} ({email}) yönetici olarak eklendi.', EN: '{name} ({email}) has been added as admin.' },
  notif_admin_pw_reset_msg:       { TR: '{name} ({email}) adlı yöneticinin şifresi genel yönetici tarafından sıfırlandı.', EN: 'Admin {name} ({email}) had their password reset by a global admin.' },
  notif_waitlist_available_msg:   { TR: '{lab} - {date} {slot} için bir yer açıldı. Lütfen randevu alın.', EN: 'A slot opened at {lab} on {date} {slot}. Please book now.' },
  notif_revoke_user_title:        { TR: '[{city}] Üyelik İptal Edildi', EN: '[{city}] Membership Revoked' },
  notif_revoke_user_msg:          { TR: '{teacher} adlı öğretmenin üyeliği iptal edildi.', EN: 'The membership of teacher {teacher} has been revoked.' },
  // Email subjects
  email_subj_account_created:     { TR: 'Hesabınız Oluşturuldu – MEB ÖGEDEP', EN: 'Account Created – MEB ÖGEDEP' },
  email_subj_password_updated:    { TR: 'Şifreniz Güncellendi – MEB ÖGEDEP', EN: 'Password Updated – MEB ÖGEDEP' },
  email_subj_membership_approved: { TR: 'Üyeliğiniz Onaylandı – MEB ÖGEDEP', EN: 'Membership Approved – MEB ÖGEDEP' },
  email_subj_appt_approved:       { TR: 'Randevunuz Onaylandı – {lab}', EN: 'Appointment Approved – {lab}' },
  email_subj_appt_cancelled:      { TR: 'Randevunuz İptal Edildi – {lab}', EN: 'Appointment Cancelled – {lab}' },
  email_subj_cancellation_denied: { TR: 'İptal Talebiniz Reddedildi – MEB ÖGEDEP', EN: 'Cancellation Request Denied – MEB ÖGEDEP' },
  email_subj_workshop_confirmed:  { TR: 'Atölye Kaydınız Oluşturuldu – {name}', EN: 'Workshop Registration Confirmed – {name}' },
  email_subj_workshop_cancelled:  { TR: 'Atölye Kaydınız İptal Edildi – {name}', EN: 'Workshop Registration Cancelled – {name}' },
  email_subj_admin_created:       { TR: 'Yönetici Hesabınız Oluşturuldu – MEB ÖGEDEP', EN: 'Admin Account Created – MEB ÖGEDEP' },
  email_subj_temp_password:       { TR: 'Geçici Şifreniz – MEB ÖGEDEP', EN: 'Temporary Password – MEB ÖGEDEP' },
  email_subj_cert_ready:          { TR: 'Sertifikanız Hazır – {workshop}', EN: 'Your Certificate is Ready – {workshop}' },
  // Email body parts
  email_dear:                     { TR: 'Sayın', EN: 'Dear' },
  email_footer_auto:              { TR: 'Bu e-posta otomatik olarak gönderilmiştir. Lütfen yanıtlamayınız.', EN: 'This email was sent automatically. Please do not reply.' },
  email_link_go_to_system:        { TR: 'Sisteme Giriş Yap', EN: 'Go to System' },
  email_lbl_password:             { TR: 'Şifre', EN: 'Password' },
  email_p_dear_participant:       { TR: 'Sayın katılımcı,', EN: 'Dear participant,' },
  email_p_cert_ready:             { TR: '<strong>{workshop}</strong> atölyesine katılımınız tamamlanmış olup sertifikanız hazırdır.', EN: 'Your attendance at the <strong>{workshop}</strong> workshop has been confirmed and your certificate is ready.' },
  email_p_cert_download:          { TR: 'Sertifikanızı indirmek için sisteme giriş yapın ve profilinizi ziyaret edin.', EN: 'Log in to the system and visit your profile to download your certificate.' },
  email_p_login_credentials:      { TR: 'Giriş bilgileriniz:', EN: 'Your login credentials:' },
  email_p_must_change_pw:         { TR: 'Sisteme giriş yaptığınızda yeni bir şifre belirlemeniz istenecektir.', EN: 'You will be prompted to set a new password upon first login.' },
  email_p_account_created:        { TR: 'MEB ÖGEDEP sistemine yönetici tarafından hesabınız oluşturulmuştur.', EN: 'An account has been created for you in the MEB ÖGEDEP system by an administrator.' },
  email_p_membership_approved:    { TR: 'MEB ÖGEDEP Öğretmen Öğrenme Laboratuvarları sistemine üyeliğiniz onaylanmıştır.', EN: 'Your membership to the MEB ÖGEDEP Teacher Learning Labs system has been approved.' },
  email_p_membership_can_book:    { TR: 'Artık sisteme giriş yaparak randevu alabilir ve atölye programlarına kayıt olabilirsiniz.', EN: 'You can now log in to book appointments and register for workshop programs.' },
  email_p_appt_approved:          { TR: '{lab} için randevunuz onaylanmıştır.', EN: 'Your appointment for {lab} has been approved.' },
  email_p_appt_date:              { TR: 'Tarih:', EN: 'Date:' },
  email_p_appt_time:              { TR: 'Saat:', EN: 'Time:' },
  email_p_appt_location:          { TR: 'Konum:', EN: 'Location:' },
  email_p_appt_cancelled:         { TR: '{lab} için {date} tarihli randevunuz yönetici tarafından iptal edilmiştir.', EN: 'Your appointment for {lab} on {date} has been cancelled by an administrator.' },
  email_p_appt_cancelled_nodate:  { TR: '{lab} için randevunuz yönetici tarafından iptal edilmiştir.', EN: 'Your appointment for {lab} has been cancelled by an administrator.' },
  email_p_book_new_appt:          { TR: 'Yeni randevu almak için sistemi ziyaret edebilirsiniz.', EN: 'You may book a new appointment through the system.' },
  email_p_cancellation_denied:    { TR: '{lab} için {date} tarihli randevunuza ait iptal talebiniz reddedilmiştir.', EN: 'Your cancellation request for the {lab} appointment on {date} has been denied.' },
  email_p_cancellation_denied_nd: { TR: '{lab} için randevunuza ait iptal talebiniz reddedilmiştir.', EN: 'Your cancellation request for the {lab} appointment has been denied.' },
  email_p_appt_still_approved:    { TR: 'Randevunuz Onaylı statüsünde devam etmektedir.', EN: 'Your appointment remains Approved.' },
  email_p_workshop_confirmed:     { TR: '"{workshop}" atölyesine kaydınız başarıyla oluşturulmuştur.', EN: 'Your registration for "{workshop}" has been confirmed.' },
  email_p_workshop_visit:         { TR: 'Atölye programı hakkında daha fazla bilgi için sistemi ziyaret edebilirsiniz.', EN: 'You can visit the system for more information about the workshop program.' },
  email_p_workshop_cancelled:     { TR: '"{workshop}" atölyesine ait kaydınız iptal edilmiştir.', EN: 'Your registration for "{workshop}" has been cancelled.' },
  email_p_workshop_other:         { TR: 'Başka bir atölye programına kayıt olmak için sistemi ziyaret edebilirsiniz.', EN: 'You can register for other workshops by visiting the system.' },
  email_p_admin_created:          { TR: 'MEB ÖGEDEP sistemine {role} olarak hesabınız oluşturulmuştur.', EN: 'An admin account has been created for you in the MEB ÖGEDEP system as {role}.' },
  email_role_global:              { TR: 'Genel Yönetici', EN: 'Global Admin' },
  email_role_city:                { TR: 'İl Yöneticisi', EN: 'Province Admin' },
  email_p_pw_reset_user:          { TR: 'Yönetici tarafından şifreniz sıfırlanmıştır. Yeni geçici şifreniz aşağıda yer almaktadır:', EN: 'Your password has been reset by an administrator. Your new temporary password is:' },
  email_p_pw_reset_admin:         { TR: 'Genel yönetici tarafından hesabınızın şifresi sıfırlanmıştır. Yeni şifreniz:', EN: 'Your account password has been reset by a global admin. Your new password is:' },
  email_p_pw_reset_request:       { TR: 'Şifre sıfırlama talebiniz alınmıştır. Geçici şifreniz:', EN: 'A password reset has been requested. Your temporary password is:' },
  email_p_pw_reset_prompt:        { TR: 'Sisteme giriş yaptığınızda yeni bir şifre belirlemeniz istenecektir.', EN: 'You will be asked to set a new password upon logging in.' },
  // AuthScreen
  forgot_pw_admin_help:           { TR: 'Şifrenizi unuttuysanız sistem yöneticinizle iletişime geçin.', EN: 'If you forgot your password, please contact your system administrator.' },
  // CertificatesTab sample data
  sample_name:                    { TR: 'Ahmet Yılmaz', EN: 'John Doe' },
  sample_workshop:                { TR: 'Örnek Atölye Adı', EN: 'Sample Workshop' },
  sample_date:                    { TR: '1 Haziran 2025', EN: '1 June 2025' },
  sample_location:                { TR: 'İstanbul', EN: 'Istanbul' },
}

export const STATUS_COLORS = {
  PENDING: 'bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-300',
  APPROVED: 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300',
  CANCELLED: 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300',
  CANCELLATION_REQUESTED: 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300',
  COMPLETED: 'bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300',
}

export const STATUS_LABELS = {
  PENDING: { TR: 'Beklemede', EN: 'Pending' },
  APPROVED: { TR: 'Onaylandı', EN: 'Approved' },
  CANCELLED: { TR: 'İptal Edildi', EN: 'Cancelled' },
  CANCELLATION_REQUESTED: { TR: 'İptal Talebi', EN: 'Cancel Requested' },
  COMPLETED: { TR: 'Tamamlandı', EN: 'Completed' },
}

export function t(key, lang = 'TR') {
  const entry = translations[key]
  if (!entry) return key
  return entry[lang] || entry['TR'] || key
}

export function getLocale(language) {
  return language === 'TR' ? 'tr-TR' : 'en-GB'
}

// Convert YYYY-MM-DD → DD.MM.YYYY
export function formatDate(dateStr) {
  if (!dateStr) return ''
  const parts = String(dateStr).split('-')
  if (parts.length !== 3) return dateStr
  return `${parts[2]}.${parts[1]}.${parts[0]}`
}

// Format epoch ms timestamp → DD.MM.YYYY HH:MM
export function formatTimestamp(ts) {
  if (!ts) return ''
  try {
    const d = new Date(Number(ts))
    const day = String(d.getDate()).padStart(2, '0')
    const month = String(d.getMonth() + 1).padStart(2, '0')
    const year = d.getFullYear()
    const hours = String(d.getHours()).padStart(2, '0')
    const mins = String(d.getMinutes()).padStart(2, '0')
    return `${day}.${month}.${year} ${hours}:${mins}`
  } catch {
    return ts
  }
}


